module.exports = {
  "name": "Edmonton",
  "type": "city",
  "cities": [
    {
      "name": "Barrhead",
      "type": "city",
      "communities": [],
    },
    {
      "name": "Beaumont",
      "type": "city",
      "communities": [
        {
          "name": "Beau Val",
          "type": "community",
        },
        // {
        //   "name": "Beaumont",
        //   "type": "community",
        // },
        {
          "name": "Beaumont Lakes",
          "type": "community",
        },
        {
          "name": "Brookside_BEAU",
          "type": "community",
        },
        {
          "name": "Chaleureuse Business Park",
          "type": "community",
        },
        {
          "name": "Citadel Ridge",
          "type": "community",
        },
        {
          "name": "Coloniale Estates_BEAU",
          "type": "community",
        },
        {
          "name": "Dansereau Meadows",
          "type": "community",
        },
        {
          "name": "Eaglemont Heights",
          "type": "community",
        },
        {
          "name": "Forest Heights",
          "type": "community",
        },
        {
          "name": "Four Season Estates_BEAU",
          "type": "community",
        },
        {
          "name": "Glenbrae Meadows",
          "type": "community",
        },
        {
          "name": "Goudreau Terrace",
          "type": "community",
        },
        {
          "name": "Montalet",
          "type": "community",
        },
        {
          "name": "Montrose Business Centre",
          "type": "community",
        },
        {
          "name": "Montrose Estates",
          "type": "community",
        },
        {
          "name": "Place Chaleureuse",
          "type": "community",
        },
        {
          "name": "Plaines Royer",
          "type": "community",
        },
        {
          "name": "Ruisseau",
          "type": "community",
        },
        {
          "name": "Triomphe Estates",
          "type": "community",
        },
      ],
    },
    {
      "name": "Bon Accord",
      "type": "city",
      "communities": [],
    },
    {
      "name": "Bonnyville Town",
      "type": "city",
      "communities": [],
    },
    {
      "name": "Bruderheim",
      "type": "city",
      "communities": [],
    },
    {
      "name": "Calmar",
      "type": "city",
      "communities": [],
    },
    {
      "name": "Camrose",
      "type": "city",
      "communities": [],
    },
    {
      "name": "Cold Lake",
      "type": "city",
      "communities": [],
    },
    {
      "name": "Devon",
      "type": "city",
      "communities": [],
    },
    {
      "name": "Drayton Valley",
      "type": "city",
      "communities": [],
    },
    {
      "name": "Elk Point",
      "type": "city",
      "communities": [],
    },
    {
      "name": "Fort Saskatchewan",
      "type": "city",
      "communities": [
        {
          "name": "Clover Park Fort Sask.",
          "type": "community",
        },
        {
          "name": "Old Fort Saskatchewan",
          "type": "community",
        },
        {
          "name": "Pineview Fort Sask.",
          "type": "community",
        },
        {
          "name": "Sherridon Heights",
          "type": "community",
        },
        {
          "name": "South Fort",
          "type": "community",
        },
        {
          "name": "Westpark_FSAS",
          "type": "community",
        },
      ],
    },
    {
      "name": "Gibbons",
      "type": "city",
      "communities": [],
    },
    {
      "name": "Lake",
      "type": "city",
      "communities": [],
    },
    {
      "name": "Lamont",
      "type": "city",
      "communities": [],
    },
    {
      "name": "Leduc",
      "type": "city",
      "communities": [
        {
          "name": "Alexandra Park",
          "type": "community",
        },
        {
          "name": "Bridgeport",
          "type": "community",
        },
        {
          "name": "Caledonia",
          "type": "community",
        },
        {
          "name": "Central Business District",
          "type": "community",
        },
        {
          "name": "Corinthia Park",
          "type": "community",
        },
        {
          "name": "Deer Valley",
          "type": "community",
        },
        {
          "name": "Lakeside Estates",
          "type": "community",
        },
        {
          "name": "Leduc Estates",
          "type": "community",
        },
        {
          "name": "Linsford Park",
          "type": "community",
        },
        {
          "name": "Meadowview Park_LEDU",
          "type": "community",
        },
        {
          "name": "North Telford",
          "type": "community",
        },
        {
          "name": "South Park",
          "type": "community",
        },
        {
          "name": "South Telford",
          "type": "community",
        },
        {
          "name": "Southfork",
          "type": "community",
        },
        {
          "name": "Suntree",
          "type": "community",
        },
        {
          "name": "Tribute",
          "type": "community",
        },
        {
          "name": "West Haven Estates",
          "type": "community",
        },
        {
          "name": "Willow Park_LEDU",
          "type": "community",
        },
        {
          "name": "Windrose",
          "type": "community",
        },
      ],
    },
    {
      "name": "Legal",
      "type": "city",
      "communities": [],
    },
    {
      "name": "Millet",
      "type": "city",
      "communities": [],
    },
    {
      "name": "Morinville",
      "type": "city",
      "communities": [],
    },
    {
      "name": "Mundare",
      "type": "city",
      "communities": [],
    },
    {
      "name": "Onoway",
      "type": "city",
      "communities": [],
    },
    {
      "name": "Redwater",
      "type": "city",
      "communities": [],
    },
    {
      "name": "Sherwood Park",
      "type": "city",
      "communities": [
        {
          "name": "Baileys Subdivision",
          "type": "community",
        },
        {
          "name": "Brentwood_CSTS",
          "type": "community",
        },
        {
          "name": "Broadmoor",
          "type": "community",
        },
        {
          "name": "Broadmoor Estates",
          "type": "community",
        },
        {
          "name": "Campbelltown Heights",
          "type": "community",
        },
        {
          "name": "Centre In The Park",
          "type": "community",
        },
        {
          "name": "Chelsea Heights",
          "type": "community",
        },
        {
          "name": "Clarkdale Meadows",
          "type": "community",
        },
        {
          "name": "Clover Bar Ranch",
          "type": "community",
        },
        {
          "name": "Country Club Estates",
          "type": "community",
        },
        {
          "name": "Craigavon",
          "type": "community",
        },
        {
          "name": "Davidson Creek",
          "type": "community",
        },
        {
          "name": "Durham Town Square",
          "type": "community",
        },
        {
          "name": "Emerald Hills",
          "type": "community",
        },
        {
          "name": "Estates of Sherwood",
          "type": "community",
        },
        {
          "name": "Executive Estates",
          "type": "community",
        },
        {
          "name": "Fountain Creek Estates",
          "type": "community",
        },
        {
          "name": "Foxboro",
          "type": "community",
        },
        {
          "name": "Foxhaven",
          "type": "community",
        },
        {
          "name": "Glen Allan",
          "type": "community",
        },
        {
          "name": "Heritage Hills",
          "type": "community",
        },
        {
          "name": "Hillsdale",
          "type": "community",
        },
        {
          "name": "Hubert Crescent",
          "type": "community",
        },
        {
          "name": "Lakeland Ridge",
          "type": "community",
        },
        {
          "name": "Lakeland Village",
          "type": "community",
        },
        {
          "name": "Lorrelind",
          "type": "community",
        },
        {
          "name": "Maplegrove",
          "type": "community",
        },
        {
          "name": "Maplewood",
          "type": "community",
        },
        {
          "name": "Mills Haven",
          "type": "community",
        },
        {
          "name": "Nottingham",
          "type": "community",
        },
        {
          "name": "Ordze Park",
          "type": "community",
        },
        {
          "name": "Poplar Lake Estates",
          "type": "community",
        },
        {
          "name": "Regency Park_CSTS",
          "type": "community",
        },
        {
          "name": "Shadow Ridge",
          "type": "community",
        },
        {
          "name": "Sherwood Heights",
          "type": "community",
        },
        {
          "name": "Shivan Park",
          "type": "community",
        },
        {
          "name": "Strathcona Village",
          "type": "community",
        },
        {
          "name": "Summerwood",
          "type": "community",
        },
        {
          "name": "The Ridge",
          "type": "community",
        },
        {
          "name": "Valley Point",
          "type": "community",
        },
        {
          "name": "Village on the Lake",
          "type": "community",
        },
        {
          "name": "Westboro",
          "type": "community",
        },
        {
          "name": "Whitecroft East",
          "type": "community",
        },
        {
          "name": "Whitecroft West",
          "type": "community",
        },
        {
          "name": "Woodbridge Farms",
          "type": "community",
        },
        {
          "name": "Wye Road Gardens",
          "type": "community",
        },
        {
          "name": "Wyecliff",
          "type": "community",
        },
      ],
    },
    {
      "name": "Spruce Grove",
      "type": "city",
      "communities": [
        {
          "name": "Aspen Glen",
          "type": "community",
        },
        {
          "name": "Brookwood",
          "type": "community",
        },
        {
          "name": "Broxton Park",
          "type": "community",
        },
        {
          "name": "Charlton Heights",
          "type": "community",
        },
        {
          "name": "City Centre",
          "type": "community",
        },
        {
          "name": "Creekside",
          "type": "community",
        },
        {
          "name": "Deer Park_SPGR",
          "type": "community",
        },
        {
          "name": "Diamond Industrial Park",
          "type": "community",
        },
        {
          "name": "Downtown Spruce Grove",
          "type": "community",
        },
        {
          "name": "Fieldstone",
          "type": "community",
        },
        {
          "name": "Grove Meadows",
          "type": "community",
        },
        {
          "name": "Harvest Ridge",
          "type": "community",
        },
        {
          "name": "Heatherglen",
          "type": "community",
        },
        {
          "name": "Hilldowns",
          "type": "community",
        },
        {
          "name": "Lakewood",
          "type": "community",
        },
        {
          "name": "Legacy Park",
          "type": "community",
        },
        {
          "name": "Linkside",
          "type": "community",
        },
        {
          "name": "Madison Industrial Park",
          "type": "community",
        },
        {
          "name": "McLaughlin_SPGR",
          "type": "community",
        },
        {
          "name": "Millgrove",
          "type": "community",
        },
        {
          "name": "Shep Industrial Park",
          "type": "community",
        },
        {
          "name": "Spruce Grove Industria Park",
          "type": "community",
        },
        {
          "name": "Spruce Ridge",
          "type": "community",
        },
        {
          "name": "Spruce Village",
          "type": "community",
        },
        {
          "name": "Spruce Woods",
          "type": "community",
        },
        {
          "name": "Stoneshire",
          "type": "community",
        },
        {
          "name": "Webber Industrial Park",
          "type": "community",
        },
        {
          "name": "West Grove",
          "type": "community",
        },
        {
          "name": "Woodhaven",
          "type": "community",
        },
        {
          "name": "Woodside_SPGR",
          "type": "community",
        },
        {
          "name": "Yellowhead Industrial Park",
          "type": "community",
        },
      ],
    },
    {
      "name": "St. Albert",
      "type": "city",
      "communities": [],
    },
    {
      "name": "St. Paul Town",
      "type": "city",
      "communities": [],
    },
    {
      "name": "Stony Plain",
      "type": "city",
      "communities": [
        {
          "name": "Brookview",
          "type": "community",
        },
        {
          "name": "Country Plains Estates",
          "type": "community",
        },
        {
          "name": "Creekside Point",
          "type": "community",
        },
        {
          "name": "Downtown_STPL",
          "type": "community",
        },
        {
          "name": "Edgeland Park",
          "type": "community",
        },
        {
          "name": "Folkstone Place",
          "type": "community",
        },
        {
          "name": "Forest Green_STPL",
          "type": "community",
        },
        {
          "name": "Genesis On The Lakes",
          "type": "community",
        },
        {
          "name": "Glens The",
          "type": "community",
        },
        {
          "name": "Graybriar",
          "type": "community",
        },
        {
          "name": "Heritage Estates_STPL",
          "type": "community",
        },
        {
          "name": "High Park_STPL",
          "type": "community",
        },
        {
          "name": "Homesteads",
          "type": "community",
        },
        {
          "name": "Jutland Ridge",
          "type": "community",
        },
        {
          "name": "Lake Westerra",
          "type": "community",
        },
        {
          "name": "Lakeview",
          "type": "community",
        },
        {
          "name": "Meridian Heights",
          "type": "community",
        },
        {
          "name": "Meridian Meadows",
          "type": "community",
        },
        {
          "name": "North Business Park",
          "type": "community",
        },
        {
          "name": "North Industrial",
          "type": "community",
        },
        {
          "name": "Northwest",
          "type": "community",
        },
        {
          "name": "Rosenthal Estates",
          "type": "community",
        },
        {
          "name": "Silverstone",
          "type": "community",
        },
        {
          "name": "South Business Park",
          "type": "community",
        },
        {
          "name": "South Creek",
          "type": "community",
        },
        {
          "name": "Southeast",
          "type": "community",
        },
        {
          "name": "Southridge_STPL",
          "type": "community",
        },
        {
          "name": "St. Andrews",
          "type": "community",
        },
        {
          "name": "The Fairways_STPL",
          "type": "community",
        },
        {
          "name": "Tiffany Greenfield",
          "type": "community",
        },
        {
          "name": "Willow Park_STPL",
          "type": "community",
        },
        {
          "name": "Woodlands_STPL",
          "type": "community",
        },
      ],
    },
    {
      "name": "Thorsby",
      "type": "city",
      "communities": [],
    },
    {
      "name": "Toname",
      "type": "city",
      "communities": [],
    },
    {
      "name": "Vegreville",
      "type": "city",
      "communities": [],
    },
    {
      "name": "West Lock",
      "type": "city",
      "communities": [],
    },
    {
      "name": "Wetaskiwin",
      "type": "city",
      "communities": [],
    },
  ],
  "areas": [
    {
      "name": "North East",
      "type": "area",
      "zones": [
        {
          "zoneId": 2,
          "name": "Zone 2",
          "type": "zone",
          "communities": [
            {
              "name": "Balwin",
              "type": "community",
              "area": "North East",
              "zone": 2,
              "code": 102000,
            },
            {
              "name": "Belvedere",
              "type": "community",
              "area": "North East",
              "zone": 2,
              "code": 101400,
            },
            {
              "name": "Casselman",
              "type": "community",
              "area": "North East",
              "zone": 2,
              "code": 101103,
            },
            {
              "name": "Delwood",
              "type": "community",
              "area": "North East",
              "zone": 2,
              "code": 101300,
            },
            {
              "name": "Evansdale",
              "type": "community",
              "area": "North East",
              "zone": 2,
              "code": 100901,
            },
            {
              "name": "Glengarry",
              "type": "community",
              "area": "North East",
              "zone": 2,
              "code": 101200,
            },
            {
              "name": "Kildare",
              "type": "community",
              "area": "North East",
              "zone": 2,
              "code": 101002,
            },
            {
              "name": "Kilkenny",
              "type": "community",
              "area": "North East",
              "zone": 2,
              "code": 101001,
            },
            {
              "name": "Killarney",
              "type": "community",
              "area": "North East",
              "zone": 2,
              "code": 101600,
            },
            {
              "name": "Miller",
              "type": "community",
              "area": "North East",
              "zone": 2,
              "code": 101104,
            },
            {
              "name": "Northmount",
              "type": "community",
              "area": "North East",
              "zone": 2,
              "code": 100902,
            },
            {
              "name": "York",
              "type": "community",
              "area": "North East",
              "zone": 2,
              "code": 101102,
            },
          ],
        },
        {
          "zoneId": 3,
          "name": "Zone 3",
          "type": "zone",
          "communities": [
            {
              "name": "Anthony Henday Horse Hill",
              "type": "community",
              "area": "North East",
              "zone": 3,
              "code": 103107,
            },
            {
              "name": "Brintnell",
              "type": "community",
              "area": "North East",
              "zone": 3,
              "code": 103104,
            },
            {
              "name": "Hollick-Kenyon",
              "type": "community",
              "area": "North East",
              "zone": 3,
              "code": 103102,
            },
            {
              "name": "Matt Berry",
              "type": "community",
              "area": "North East",
              "zone": 3,
              "code": 103101,
            },
            {
              "name": "McConachie Area",
              "type": "community",
              "area": "North East",
              "zone": 3,
              "code": 103103,
            },
          ],
        },
        {
          "zoneId": 6,
          "name": "Zone 6",
          "type": "zone",
          "communities": [
            {
              "name": "Industrial Heights",
              "type": "community",
              "area": "North East",
              "zone": 6,
              "code": 105600,
            },
            {
              "name": "Montrose",
              "type": "community",
              "area": "North East",
              "zone": 6,
              "code": 104600,
            },
            {
              "name": "Newton",
              "type": "community",
              "area": "North East",
              "zone": 6,
              "code": 105700,
            },
          ],
        },
        {
          "zoneId": 23,
          "name": "Zone 23",
          "type": "zone",
          "communities": [
            {
              "name": "Abbottsfield",
              "type": "community",
              "area": "North East",
              "zone": 23,
              "code": 107800,
            },
            {
              "name": "Beacon Heights",
              "type": "community",
              "area": "North East",
              "zone": 23,
              "code": 107600,
            },
            {
              "name": "Bergman",
              "type": "community",
              "area": "North East",
              "zone": 23,
              "code": 107500,
            },
            {
              "name": "Beverly Heights",
              "type": "community",
              "area": "North East",
              "zone": 23,
              "code": 107900,
            },
            {
              "name": "River Valley Rundle",
              "type": "community",
              "area": "North East",
              "zone": 23,
              "code": 107700,
            },
            {
              "name": "Rundle Heights",
              "type": "community",
              "area": "North East",
              "zone": 23,
              "code": 108100,
            },
          ],
        },
        {
          "zoneId": 28,
          "name": "Zone 28",
          "type": "zone",
          "communities": [
            {
              "name": "Anthony Henday Lake District",
              "type": "community",
              "area": "North East",
              "zone": 28,
              "code": 100011,
            },
            {
              "name": "Belle Rive",
              "type": "community",
              "area": "North East",
              "zone": 28,
              "code": 100007,
            },
            {
              "name": "Eaux Claires",
              "type": "community",
              "area": "North East",
              "zone": 28,
              "code": 100006,
            },
            {
              "name": "Klarvatten",
              "type": "community",
              "area": "North East",
              "zone": 28,
              "code": 100002,
            },
            {
              "name": "Lago Lindo",
              "type": "community",
              "area": "North East",
              "zone": 28,
              "code": 100001,
            },
            {
              "name": "Mayliewan",
              "type": "community",
              "area": "North East",
              "zone": 28,
              "code": 100008,
            },
            {
              "name": "Ozerna",
              "type": "community",
              "area": "North East",
              "zone": 28,
              "code": 100009,
            },
            {
              "name": "Schonsee",
              "type": "community",
              "area": "North East",
              "zone": 28,
              "code": 100005,
            },
          ],
        },
        {
          "zoneId": 35,
          "name": "Zone 35",
          "type": "zone",
          "communities": [
            {
              "name": "Anthony Henday Clareview",
              "type": "community",
              "area": "North East",
              "zone": 35,
              "code": 103005,
            },
            {
              "name": "Bannerman",
              "type": "community",
              "area": "North East",
              "zone": 35,
              "code": 102904,
            },
            {
              "name": "Belmont",
              "type": "community",
              "area": "North East",
              "zone": 35,
              "code": 102906,
            },
            {
              "name": "Canon Ridge",
              "type": "community",
              "area": "North East",
              "zone": 35,
              "code": 103003,
            },
            {
              "name": "Clareview Town Centre",
              "type": "community",
              "area": "North East",
              "zone": 35,
              "code": 102909,
            },
            {
              "name": "Fraser",
              "type": "community",
              "area": "North East",
              "zone": 35,
              "code": 102902,
            },
            {
              "name": "Hairsine",
              "type": "community",
              "area": "North East",
              "zone": 35,
              "code": 102903,
            },
            {
              "name": "Homesteader",
              "type": "community",
              "area": "North East",
              "zone": 35,
              "code": 103001,
            },
            {
              "name": "Kernohan",
              "type": "community",
              "area": "North East",
              "zone": 35,
              "code": 102907,
            },
            {
              "name": "Kirkness",
              "type": "community",
              "area": "North East",
              "zone": 35,
              "code": 102901,
            },
            {
              "name": "Overlanders",
              "type": "community",
              "area": "North East",
              "zone": 35,
              "code": 103002,
            },
            {
              "name": "River Valley Hermitage",
              "type": "community",
              "area": "North East",
              "zone": 35,
              "code": 103004,
            },
            {
              "name": "Sifton Park",
              "type": "community",
              "area": "North East",
              "zone": 35,
              "code": 102905,
            },
          ],
        },
        {
          "zoneId": 51,
          "name": "Zone 51",
          "type": "zone",
          "communities": [
            {
              "name": "Evergreen_EDMO",
              "type": "community",
              "area": "North East",
              "zone": 51,
              "code": 510300,
            },
            {
              "name": "Rural North East Horse Hills",
              "type": "community",
              "area": "North East",
              "zone": 51,
              "code": 510100,
            },
            {
              "name": "Rural North East South Sturgeon",
              "type": "community",
              "area": "North East",
              "zone": 51,
              "code": 510200,
            },
          ],
        },
      ],
    },
    {
      "name": "North West",
      "type": "area",
      "zones": [
        {
          "zoneId": 1,
          "name": "Zone 1",
          "type": "zone",
          "communities": [
            {
              "name": "Athlone",
              "type": "community",
              "area": "North West",
              "zone": 1,
              "code": 1400,
            },
            {
              "name": "Calder",
              "type": "community",
              "area": "North West",
              "zone": 1,
              "code": 1500,
            },
            {
              "name": "Kensington",
              "type": "community",
              "area": "North West",
              "zone": 1,
              "code": 1200,
            },
            {
              "name": "Lauderdale",
              "type": "community",
              "area": "North West",
              "zone": 1,
              "code": 1800,
            },
            {
              "name": "Rosslyn",
              "type": "community",
              "area": "North West",
              "zone": 1,
              "code": 1300,
            },
            {
              "name": "Wellington",
              "type": "community",
              "area": "North West",
              "zone": 1,
              "code": 1100,
            },
          ],
        },
        {
          "zoneId": 27,
          "name": "Zone 27",
          "type": "zone",
          "communities": [
            {
              "name": "Albany",
              "type": "community",
              "area": "North West",
              "zone": 27,
              "code": 302,
            },
            {
              "name": "Anthony Henday Castledowns",
              "type": "community",
              "area": "North West",
              "zone": 27,
              "code": 303,
            },
            {
              "name": "Baranow",
              "type": "community",
              "area": "North West",
              "zone": 27,
              "code": 110,
            },
            {
              "name": "Baturyn",
              "type": "community",
              "area": "North West",
              "zone": 27,
              "code": 201,
            },
            {
              "name": "Beaumaris",
              "type": "community",
              "area": "North West",
              "zone": 27,
              "code": 203,
            },
            {
              "name": "Caernarvon",
              "type": "community",
              "area": "North West",
              "zone": 27,
              "code": 102,
            },
            {
              "name": "Canossa",
              "type": "community",
              "area": "North West",
              "zone": 27,
              "code": 104,
            },
            {
              "name": "Carlisle",
              "type": "community",
              "area": "North West",
              "zone": 27,
              "code": 103,
            },
            {
              "name": "Carlton",
              "type": "community",
              "area": "North West",
              "zone": 27,
              "code": 206,
            },
            {
              "name": "Chambery",
              "type": "community",
              "area": "North West",
              "zone": 27,
              "code": 106,
            },
            {
              "name": "Cumberland",
              "type": "community",
              "area": "North West",
              "zone": 27,
              "code": 108,
            },
            {
              "name": "Dunluce",
              "type": "community",
              "area": "North West",
              "zone": 27,
              "code": 101,
            },
            {
              "name": "Elsinore",
              "type": "community",
              "area": "North West",
              "zone": 27,
              "code": 204,
            },
            {
              "name": "Goodridge Corners",
              "type": "community",
              "area": "North West",
              "zone": 27,
              "code": 111,
            },
            {
              "name": "Griesbach",
              "type": "community",
              "area": "North West",
              "zone": 27,
              "code": 112,
            },
            {
              "name": "Hudson",
              "type": "community",
              "area": "North West",
              "zone": 27,
              "code": 205,
            },
            {
              "name": "Lorelei",
              "type": "community",
              "area": "North West",
              "zone": 27,
              "code": 202,
            },
            {
              "name": "Oxford",
              "type": "community",
              "area": "North West",
              "zone": 27,
              "code": 107,
            },
            {
              "name": "Pembina",
              "type": "community",
              "area": "North West",
              "zone": 27,
              "code": 109,
            },
            {
              "name": "Rapperswill",
              "type": "community",
              "area": "North West",
              "zone": 27,
              "code": 105,
            },
          ],
        },
        {
          "zoneId": 40,
          "name": "Zone 40",
          "type": "zone",
          "communities": [
            {
              "name": "Anthony Henday",
              "type": "community",
              "area": "North West",
              "zone": 40,
              "code": 32904,
            },
            {
              "name": "Anthony Henday Big Lake",
              "type": "community",
              "area": "North West",
              "zone": 40,
              "code": 32908,
            },
            {
              "name": "Anthony Henday Mistatim",
              "type": "community",
              "area": "North West",
              "zone": 40,
              "code": 32907,
            },
            {
              "name": "Kinokamau Plains Area",
              "type": "community",
              "area": "North West",
              "zone": 40,
              "code": 32906,
            },
          ],
        },
        {
          "zoneId": 59,
          "name": "Zone 59",
          "type": "zone",
          "communities": [
            {
              "name": "Hawks Ridge",
              "type": "community",
              "area": "North West",
              "zone": 59,
              "code": 590500,
            },
            {
              "name": "Rural West Big Lake",
              "type": "community",
              "area": "North West",
              "zone": 59,
              "code": 590000,
            },
            {
              "name": "Starling",
              "type": "community",
              "area": "North West",
              "zone": 59,
              "code": 590600,
            },
            {
              "name": "Trumpeter Area",
              "type": "community",
              "area": "North West",
              "zone": 59,
              "code": 590400,
            },
          ],
        },
      ],
    },
    {
      "name": "Central",
      "type": "area",
      "zones": [
        {
          "zoneId": 4,
          "name": "Zone 4",
          "type": "zone",
          "communities": [
            {
              "name": "Dovercourt",
              "type": "community",
              "area": "Central",
              "zone": 4,
              "code": 2100,
            },
            {
              "name": "Prince Charles",
              "type": "community",
              "area": "Central",
              "zone": 4,
              "code": 2400,
            },
            {
              "name": "Sherbrooke",
              "type": "community",
              "area": "Central",
              "zone": 4,
              "code": 2200,
            },
          ],
        },
        {
          "zoneId": 5,
          "name": "Zone 5",
          "type": "zone",
          "communities": [
            {
              "name": "Alberta Avenue",
              "type": "community",
              "area": "Central",
              "zone": 5,
              "code": 103300,
            },
            {
              "name": "Delton",
              "type": "community",
              "area": "Central",
              "zone": 5,
              "code": 103700,
            },
            {
              "name": "Eastwood",
              "type": "community",
              "area": "Central",
              "zone": 5,
              "code": 104800,
            },
            {
              "name": "Elmwood Park",
              "type": "community",
              "area": "Central",
              "zone": 5,
              "code": 104700,
            },
            {
              "name": "Parkdale_EDMO",
              "type": "community",
              "area": "Central",
              "zone": 5,
              "code": 104300,
            },
          ],
        },
        {
          "zoneId": 7,
          "name": "Zone 7",
          "type": "zone",
          "communities": [
            {
              "name": "Inglewood_EDMO",
              "type": "community",
              "area": "Central",
              "zone": 7,
              "code": 3000,
            },
            {
              "name": "North Glenora",
              "type": "community",
              "area": "Central",
              "zone": 7,
              "code": 3100,
            },
            {
              "name": "Westmount",
              "type": "community",
              "area": "Central",
              "zone": 7,
              "code": 2900,
            },
            {
              "name": "Woodcroft",
              "type": "community",
              "area": "Central",
              "zone": 7,
              "code": 2700,
            },
          ],
        },
        {
          "zoneId": 8,
          "name": "Zone 8",
          "type": "zone",
          "communities": [
            {
              "name": "Central McDougall",
              "type": "community",
              "area": "Central",
              "zone": 8,
              "code": 3604,
            },
            {
              "name": "Prince Rupert",
              "type": "community",
              "area": "Central",
              "zone": 8,
              "code": 3601,
            },
            {
              "name": "Queen Mary Park",
              "type": "community",
              "area": "Central",
              "zone": 8,
              "code": 3603,
            },
            {
              "name": "Spruce Avenue",
              "type": "community",
              "area": "Central",
              "zone": 8,
              "code": 3602,
            },
            {
              "name": "Westwood_EDMO",
              "type": "community",
              "area": "Central",
              "zone": 8,
              "code": 103900,
            },
            {
              "name": "Yellowhead Corridor East",
              "type": "community",
              "area": "Central",
              "zone": 8,
              "code": 104001,
            },
            {
              "name": "Yellowhead Corridor West",
              "type": "community",
              "area": "Central",
              "zone": 8,
              "code": 104000,
            },
          ],
        },
        {
          "zoneId": 9,
          "name": "Zone 9",
          "type": "zone",
          "communities": [
            {
              "name": "Bellevue",
              "type": "community",
              "area": "Central",
              "zone": 9,
              "code": 106200,
            },
            {
              "name": "Cromdale",
              "type": "community",
              "area": "Central",
              "zone": 9,
              "code": 105900,
            },
            {
              "name": "Edmonton Northlands",
              "type": "community",
              "area": "Central",
              "zone": 9,
              "code": 106600,
            },
            {
              "name": "Highlands",
              "type": "community",
              "area": "Central",
              "zone": 9,
              "code": 106500,
            },
            {
              "name": "River Valley Highlands",
              "type": "community",
              "area": "Central",
              "zone": 9,
              "code": 107400,
            },
            {
              "name": "River Valley Kinnaird",
              "type": "community",
              "area": "Central",
              "zone": 9,
              "code": 106300,
            },
            {
              "name": "Virginia Park",
              "type": "community",
              "area": "Central",
              "zone": 9,
              "code": 106800,
            },
          ],
        },
        {
          "zoneId": 11,
          "name": "Zone 11",
          "type": "zone",
          "communities": [
            {
              "name": "Glenora",
              "type": "community",
              "area": "Central",
              "zone": 11,
              "code": 8600,
            },
            {
              "name": "River Valley Glenora",
              "type": "community",
              "area": "Central",
              "zone": 11,
              "code": 8900,
            },
          ],
        },
        {
          "zoneId": 12,
          "name": "Zone 12",
          "type": "zone",
          "communities": [
            {
              "name": "Downtown_EDMO",
              "type": "community",
              "area": "Central",
              "zone": 12,
              "code": 3606,
            },
            {
              "name": "Oliver",
              "type": "community",
              "area": "Central",
              "zone": 12,
              "code": 3605,
            },
            {
              "name": "River Valley Victoria",
              "type": "community",
              "area": "Central",
              "zone": 12,
              "code": 3609,
            },
            {
              "name": "Rossdale",
              "type": "community",
              "area": "Central",
              "zone": 12,
              "code": 108500,
            },
          ],
        },
        {
          "zoneId": 13,
          "name": "Zone 13",
          "type": "zone",
          "communities": [
            {
              "name": "Boyle Street",
              "type": "community",
              "area": "Central",
              "zone": 13,
              "code": 109500,
            },
            {
              "name": "McCauley",
              "type": "community",
              "area": "Central",
              "zone": 13,
              "code": 109400,
            },
            {
              "name": "Riverdale",
              "type": "community",
              "area": "Central",
              "zone": 13,
              "code": 109200,
            },
          ],
        },
      ],
    },
    {
      "name": "West",
      "type": "area",
      "zones": [
        {
          "zoneId": 10,
          "name": "Zone 10",
          "type": "zone",
          "communities": [
            {
              "name": "Crestwood",
              "type": "community",
              "area": "West",
              "zone": 10,
              "code": 7900,
            },
            {
              "name": "Laurier Heights",
              "type": "community",
              "area": "West",
              "zone": 10,
              "code": 8200,
            },
            {
              "name": "Parkview",
              "type": "community",
              "area": "West",
              "zone": 10,
              "code": 8000,
            },
            {
              "name": "River Valley Capitol Hill",
              "type": "community",
              "area": "West",
              "zone": 10,
              "code": 7800,
            },
            {
              "name": "River Valley Laurier",
              "type": "community",
              "area": "West",
              "zone": 10,
              "code": 8800,
            },
          ],
        },
        {
          "zoneId": 20,
          "name": "Zone 20",
          "type": "zone",
          "communities": [
            {
              "name": "Aldergrove",
              "type": "community",
              "area": "West",
              "zone": 20,
              "code": 3903,
            },
            {
              "name": "Anthony Henday South West",
              "type": "community",
              "area": "West",
              "zone": 20,
              "code": 4309,
            },
            {
              "name": "Belmead",
              "type": "community",
              "area": "West",
              "zone": 20,
              "code": 3902,
            },
            {
              "name": "Callingwood North",
              "type": "community",
              "area": "West",
              "zone": 20,
              "code": 4201,
            },
            {
              "name": "Callingwood South",
              "type": "community",
              "area": "West",
              "zone": 20,
              "code": 4202,
            },
            {
              "name": "Cameron Heights_EDMO",
              "type": "community",
              "area": "West",
              "zone": 20,
              "code": 4306,
            },
            {
              "name": "Dechene",
              "type": "community",
              "area": "West",
              "zone": 20,
              "code": 4302,
            },
            {
              "name": "Donsdale",
              "type": "community",
              "area": "West",
              "zone": 20,
              "code": 4305,
            },
            {
              "name": "Gariepy",
              "type": "community",
              "area": "West",
              "zone": 20,
              "code": 4303,
            },
            {
              "name": "Jamieson Place",
              "type": "community",
              "area": "West",
              "zone": 20,
              "code": 4301,
            },
            {
              "name": "La Perle",
              "type": "community",
              "area": "West",
              "zone": 20,
              "code": 3901,
            },
            {
              "name": "Lymburn",
              "type": "community",
              "area": "West",
              "zone": 20,
              "code": 4101,
            },
            {
              "name": "Ormsby Place",
              "type": "community",
              "area": "West",
              "zone": 20,
              "code": 4102,
            },
            {
              "name": "River Valley Cameron",
              "type": "community",
              "area": "West",
              "zone": 20,
              "code": 4308,
            },
            {
              "name": "Summerlea",
              "type": "community",
              "area": "West",
              "zone": 20,
              "code": 4001,
            },
            {
              "name": "Terra Losa",
              "type": "community",
              "area": "West",
              "zone": 20,
              "code": 4003,
            },
            {
              "name": "Thorncliffe_EDMO",
              "type": "community",
              "area": "West",
              "zone": 20,
              "code": 4002,
            },
          ],
        },
        {
          "zoneId": 21,
          "name": "Zone 21",
          "type": "zone",
          "communities": [
            {
              "name": "Britannia Youngstown",
              "type": "community",
              "area": "West",
              "zone": 21,
              "code": 5400,
            },
            {
              "name": "Canora",
              "type": "community",
              "area": "West",
              "zone": 21,
              "code": 5600,
            },
            {
              "name": "Grovenor",
              "type": "community",
              "area": "West",
              "zone": 21,
              "code": 3300,
            },
            {
              "name": "High Park_EDMO",
              "type": "community",
              "area": "West",
              "zone": 21,
              "code": 5201,
            },
            {
              "name": "Mayfield",
              "type": "community",
              "area": "West",
              "zone": 21,
              "code": 5100,
            },
            {
              "name": "McQueen",
              "type": "community",
              "area": "West",
              "zone": 21,
              "code": 3200,
            },
          ],
        },
        {
          "zoneId": 22,
          "name": "Zone 22",
          "type": "zone",
          "communities": [
            {
              "name": "Elmwood",
              "type": "community",
              "area": "West",
              "zone": 22,
              "code": 6600,
            },
            {
              "name": "Glenwood",
              "type": "community",
              "area": "West",
              "zone": 22,
              "code": 5900,
            },
            {
              "name": "Jasper Park",
              "type": "community",
              "area": "West",
              "zone": 22,
              "code": 6400,
            },
            {
              "name": "Lynnwood",
              "type": "community",
              "area": "West",
              "zone": 22,
              "code": 6700,
            },
            {
              "name": "Meadowlark Park_EDMO",
              "type": "community",
              "area": "West",
              "zone": 22,
              "code": 6200,
            },
            {
              "name": "Oleskiw",
              "type": "community",
              "area": "West",
              "zone": 22,
              "code": 7300,
            },
            {
              "name": "Patricia Heights",
              "type": "community",
              "area": "West",
              "zone": 22,
              "code": 7000,
            },
            {
              "name": "Quesnell Heights",
              "type": "community",
              "area": "West",
              "zone": 22,
              "code": 8300,
            },
            {
              "name": "Rio Terrace",
              "type": "community",
              "area": "West",
              "zone": 22,
              "code": 7100,
            },
            {
              "name": "River Valley Oleskiw",
              "type": "community",
              "area": "West",
              "zone": 22,
              "code": 7500,
            },
            {
              "name": "Sherwood",
              "type": "community",
              "area": "West",
              "zone": 22,
              "code": 7400,
            },
            {
              "name": "West Jasper Place",
              "type": "community",
              "area": "West",
              "zone": 22,
              "code": 6100,
            },
            {
              "name": "West Meadowlark Park",
              "type": "community",
              "area": "West",
              "zone": 22,
              "code": 6300,
            },
            {
              "name": "Westridge",
              "type": "community",
              "area": "West",
              "zone": 22,
              "code": 7200,
            },
          ],
        },
        {
          "zoneId": 58,
          "name": "Zone 58",
          "type": "zone",
          "communities": [
            {
              "name": "Breckenridge Greens",
              "type": "community",
              "area": "West",
              "zone": 58,
              "code": 580100,
            },
            {
              "name": "Glastonbury",
              "type": "community",
              "area": "West",
              "zone": 58,
              "code": 580200,
            },
            {
              "name": "Potter Greens",
              "type": "community",
              "area": "West",
              "zone": 58,
              "code": 580600,
            },
            {
              "name": "Secord",
              "type": "community",
              "area": "West",
              "zone": 58,
              "code": 581100,
            },
            {
              "name": "Stewart Greens",
              "type": "community",
              "area": "West",
              "zone": 58,
              "code": 581000,
            },
            {
              "name": "Suder Greens",
              "type": "community",
              "area": "West",
              "zone": 58,
              "code": 580900,
            },
            {
              "name": "Webber Greens",
              "type": "community",
              "area": "West",
              "zone": 58,
              "code": 580800,
            },
          ],
        },
      ],
    },
    {
      "name": "South West",
      "type": "area",
      "zones": [
        {
          "zoneId": 14,
          "name": "Zone 14",
          "type": "zone",
          "communities": [
            {
              "name": "Anthony Henday Terwillegar",
              "type": "community",
              "area": "South West",
              "zone": 14,
              "code": 202102,
            },
            {
              "name": "Brander Gardens",
              "type": "community",
              "area": "South West",
              "zone": 14,
              "code": 200401,
            },
            {
              "name": "Brookside",
              "type": "community",
              "area": "South West",
              "zone": 14,
              "code": 200402,
            },
            {
              "name": "Bulyea Heights",
              "type": "community",
              "area": "South West",
              "zone": 14,
              "code": 200405,
            },
            {
              "name": "Carter Crest",
              "type": "community",
              "area": "South West",
              "zone": 14,
              "code": 200408,
            },
            {
              "name": "Falconer Heights",
              "type": "community",
              "area": "South West",
              "zone": 14,
              "code": 200407,
            },
            {
              "name": "Haddow",
              "type": "community",
              "area": "South West",
              "zone": 14,
              "code": 202101,
            },
            {
              "name": "Henderson Estates",
              "type": "community",
              "area": "South West",
              "zone": 14,
              "code": 200406,
            },
            {
              "name": "Hodgson",
              "type": "community",
              "area": "South West",
              "zone": 14,
              "code": 201102,
            },
            {
              "name": "Leger",
              "type": "community",
              "area": "South West",
              "zone": 14,
              "code": 200410,
            },
            {
              "name": "MacTaggart",
              "type": "community",
              "area": "South West",
              "zone": 14,
              "code": 140100,
            },
            {
              "name": "Magrath Heights",
              "type": "community",
              "area": "South West",
              "zone": 14,
              "code": 140200,
            },
            {
              "name": "Ogilvie Ridge",
              "type": "community",
              "area": "South West",
              "zone": 14,
              "code": 200409,
            },
            {
              "name": "Ramsay Heights",
              "type": "community",
              "area": "South West",
              "zone": 14,
              "code": 200403,
            },
            {
              "name": "Rhatigan Ridge",
              "type": "community",
              "area": "South West",
              "zone": 14,
              "code": 200404,
            },
            {
              "name": "River Valley Fort Edmonton",
              "type": "community",
              "area": "South West",
              "zone": 14,
              "code": 140400,
            },
            {
              "name": "River Valley Terwillegar",
              "type": "community",
              "area": "South West",
              "zone": 14,
              "code": 200412,
            },
            {
              "name": "River Valley Whitemud",
              "type": "community",
              "area": "South West",
              "zone": 14,
              "code": 200413,
            },
            {
              "name": "South Terwillegar",
              "type": "community",
              "area": "South West",
              "zone": 14,
              "code": 200415,
            },
            {
              "name": "Terwillegar Towne",
              "type": "community",
              "area": "South West",
              "zone": 14,
              "code": 201200,
            },
            {
              "name": "Whitemud Creek Ravine North",
              "type": "community",
              "area": "South West",
              "zone": 14,
              "code": 200414,
            },
            {
              "name": "Whitemud Creek Ravine South",
              "type": "community",
              "area": "South West",
              "zone": 14,
              "code": 140300,
            },
          ],
        },
        {
          "zoneId": 16,
          "name": "Zone 16",
          "type": "zone",
          "communities": [
            {
              "name": "Anthony Henday South",
              "type": "community",
              "area": "South West",
              "zone": 16,
              "code": 206400,
            },
            {
              "name": "Aspen Gardens",
              "type": "community",
              "area": "South West",
              "zone": 16,
              "code": 200901,
            },
            {
              "name": "Blue Quill",
              "type": "community",
              "area": "South West",
              "zone": 16,
              "code": 201002,
            },
            {
              "name": "Blue Quill Estates",
              "type": "community",
              "area": "South West",
              "zone": 16,
              "code": 201003,
            },
            {
              "name": "Duggan",
              "type": "community",
              "area": "South West",
              "zone": 16,
              "code": 206001,
            },
            {
              "name": "Ermineskin",
              "type": "community",
              "area": "South West",
              "zone": 16,
              "code": 206102,
            },
            {
              "name": "Greenfield",
              "type": "community",
              "area": "South West",
              "zone": 16,
              "code": 200903,
            },
            {
              "name": "Keheewin",
              "type": "community",
              "area": "South West",
              "zone": 16,
              "code": 206202,
            },
            {
              "name": "Rideau Park_EDMO",
              "type": "community",
              "area": "South West",
              "zone": 16,
              "code": 206002,
            },
            {
              "name": "Royal Gardens_EDMO",
              "type": "community",
              "area": "South West",
              "zone": 16,
              "code": 200902,
            },
            {
              "name": "Skyrattler",
              "type": "community",
              "area": "South West",
              "zone": 16,
              "code": 206201,
            },
            {
              "name": "Steinhauer",
              "type": "community",
              "area": "South West",
              "zone": 16,
              "code": 206101,
            },
            {
              "name": "Sweet Grass",
              "type": "community",
              "area": "South West",
              "zone": 16,
              "code": 201001,
            },
            {
              "name": "Twin Brooks",
              "type": "community",
              "area": "South West",
              "zone": 16,
              "code": 206300,
            },
            {
              "name": "Westbrook Estate",
              "type": "community",
              "area": "South West",
              "zone": 16,
              "code": 200904,
            },
          ],
        },
        {
          "zoneId": 55,
          "name": "Zone 55",
          "type": "zone",
          "communities": [
            {
              "name": "Allard",
              "type": "community",
              "area": "South West",
              "zone": 55,
              "code": 550800,
            },
            {
              "name": "Blackburne",
              "type": "community",
              "area": "South West",
              "zone": 55,
              "code": 550100,
            },
            {
              "name": "Blackmud Creek",
              "type": "community",
              "area": "South West",
              "zone": 55,
              "code": 550200,
            },
            {
              "name": "Blackmud Creek Ravine",
              "type": "community",
              "area": "South West",
              "zone": 55,
              "code": 551400,
            },
            {
              "name": "Callaghan",
              "type": "community",
              "area": "South West",
              "zone": 55,
              "code": 550700,
            },
            {
              "name": "Cashman",
              "type": "community",
              "area": "South West",
              "zone": 55,
              "code": 552000,
            },
            {
              "name": "Hays Ridge Area",
              "type": "community",
              "area": "South West",
              "zone": 55,
              "code": 551300,
            },
            {
              "name": "Heritage Valley Area",
              "type": "community",
              "area": "South West",
              "zone": 55,
              "code": 550600,
            },
            {
              "name": "Heritage Valley Area East",
              "type": "community",
              "area": "South West",
              "zone": 55,
              "code": 551200,
            },
            {
              "name": "Heritage Valley Town Centre Area",
              "type": "community",
              "area": "South West",
              "zone": 55,
              "code": 551100,
            },
            {
              "name": "Richford",
              "type": "community",
              "area": "South West",
              "zone": 55,
              "code": 550300,
            },
            {
              "name": "Rutherford",
              "type": "community",
              "area": "South West",
              "zone": 55,
              "code": 550500,
            },
          ],
        },
        {
          "zoneId": 56,
          "name": "Zone 56",
          "type": "zone",
          "communities": [
            {
              "name": "Ambleside",
              "type": "community",
              "area": "South West",
              "zone": 56,
              "code": 560200,
            },
            {
              "name": "Glenridding Area",
              "type": "community",
              "area": "South West",
              "zone": 56,
              "code": 560500,
            },
            {
              "name": "Keswick Area",
              "type": "community",
              "area": "South West",
              "zone": 56,
              "code": 560700,
            },
            {
              "name": "River Valley Windermere",
              "type": "community",
              "area": "South West",
              "zone": 56,
              "code": 560400,
            },
            {
              "name": "Windermere",
              "type": "community",
              "area": "South West",
              "zone": 56,
              "code": 560100,
            },
            {
              "name": "Windermere Area",
              "type": "community",
              "area": "South West",
              "zone": 56,
              "code": 560300,
            },
          ],
        },
      ],
    },
    {
      "name": "South Central",
      "type": "area",
      "zones": [
        {
          "zoneId": 15,
          "name": "Zone 15",
          "type": "zone",
          "communities": [
            {
              "name": "Allendale",
              "type": "community",
              "area": "South Central",
              "zone": 15,
              "code": 205900,
            },
            {
              "name": "Belgravia",
              "type": "community",
              "area": "South Central",
              "zone": 15,
              "code": 200300,
            },
            {
              "name": "Empire Park",
              "type": "community",
              "area": "South Central",
              "zone": 15,
              "code": 183700,
            },
            {
              "name": "Garneau",
              "type": "community",
              "area": "South Central",
              "zone": 15,
              "code": 205000,
            },
            {
              "name": "Grandview Heights_EDMO",
              "type": "community",
              "area": "South Central",
              "zone": 15,
              "code": 200501,
            },
            {
              "name": "Lansdowne",
              "type": "community",
              "area": "South Central",
              "zone": 15,
              "code": 200600,
            },
            {
              "name": "Lendrum Place",
              "type": "community",
              "area": "South Central",
              "zone": 15,
              "code": 200700,
            },
            {
              "name": "Malmo Plains",
              "type": "community",
              "area": "South Central",
              "zone": 15,
              "code": 200800,
            },
            {
              "name": "McKernan",
              "type": "community",
              "area": "South Central",
              "zone": 15,
              "code": 205601,
            },
            {
              "name": "Mill Creek Ravine North",
              "type": "community",
              "area": "South Central",
              "zone": 15,
              "code": 184600,
            },
            {
              "name": "Parkallen_EDMO",
              "type": "community",
              "area": "South Central",
              "zone": 15,
              "code": 205600,
            },
            {
              "name": "Pleasantview_EDMO",
              "type": "community",
              "area": "South Central",
              "zone": 15,
              "code": 205800,
            },
            {
              "name": "Queen Alexandra",
              "type": "community",
              "area": "South Central",
              "zone": 15,
              "code": 205100,
            },
            {
              "name": "River Valley Mayfair",
              "type": "community",
              "area": "South Central",
              "zone": 15,
              "code": 150100,
            },
            {
              "name": "River Valley Walterdale",
              "type": "community",
              "area": "South Central",
              "zone": 15,
              "code": 205300,
            },
            {
              "name": "Strathcona",
              "type": "community",
              "area": "South Central",
              "zone": 15,
              "code": 205200,
            },
            {
              "name": "Windsor Park_EDMO",
              "type": "community",
              "area": "South Central",
              "zone": 15,
              "code": 200000,
            },
          ],
        },
        {
          "zoneId": 17,
          "name": "Zone 17",
          "type": "zone",
          "communities": [
            {
              "name": "Argyll",
              "type": "community",
              "area": "South Central",
              "zone": 17,
              "code": 184800,
            },
            {
              "name": "Avonmore",
              "type": "community",
              "area": "South Central",
              "zone": 17,
              "code": 184900,
            },
            {
              "name": "Hazeldean",
              "type": "community",
              "area": "South Central",
              "zone": 17,
              "code": 184700,
            },
            {
              "name": "King Edward Park",
              "type": "community",
              "area": "South Central",
              "zone": 17,
              "code": 184100,
            },
            {
              "name": "Mill Creek Ravine South",
              "type": "community",
              "area": "South Central",
              "zone": 17,
              "code": 184200,
            },
            {
              "name": "Ritchie",
              "type": "community",
              "area": "South Central",
              "zone": 17,
              "code": 183800,
            },
          ],
        },
        {
          "zoneId": 18,
          "name": "Zone 18",
          "type": "zone",
          "communities": [
            {
              "name": "Bonnie Doon",
              "type": "community",
              "area": "South Central",
              "zone": 18,
              "code": 182500,
            },
            {
              "name": "Cloverdale",
              "type": "community",
              "area": "South Central",
              "zone": 18,
              "code": 181100,
            },
            {
              "name": "Holyrood",
              "type": "community",
              "area": "South Central",
              "zone": 18,
              "code": 183100,
            },
            {
              "name": "Idylwylde",
              "type": "community",
              "area": "South Central",
              "zone": 18,
              "code": 183300,
            },
            {
              "name": "Kenilworth",
              "type": "community",
              "area": "South Central",
              "zone": 18,
              "code": 183202,
            },
            {
              "name": "Ottewell",
              "type": "community",
              "area": "South Central",
              "zone": 18,
              "code": 183600,
            },
            {
              "name": "Strathearn",
              "type": "community",
              "area": "South Central",
              "zone": 18,
              "code": 181700,
            },
          ],
        },
        {
          "zoneId": 19,
          "name": "Zone 19",
          "type": "zone",
          "communities": [
            {
              "name": "Capilano",
              "type": "community",
              "area": "South Central",
              "zone": 19,
              "code": 180501,
            },
            {
              "name": "Forest Heights_EDMO",
              "type": "community",
              "area": "South Central",
              "zone": 19,
              "code": 180100,
            },
            {
              "name": "Fulton Place",
              "type": "community",
              "area": "South Central",
              "zone": 19,
              "code": 180502,
            },
            {
              "name": "Gold Bar",
              "type": "community",
              "area": "South Central",
              "zone": 19,
              "code": 180503,
            },
            {
              "name": "River Valley Gold Bar",
              "type": "community",
              "area": "South Central",
              "zone": 19,
              "code": 180504,
            },
            {
              "name": "River Valley Riverside",
              "type": "community",
              "area": "South Central",
              "zone": 19,
              "code": 180505,
            },
            {
              "name": "Terrace Heights_EDMO",
              "type": "community",
              "area": "South Central",
              "zone": 19,
              "code": 180400,
            },
          ],
        },
      ],
    },
    {
      "name": "South East",
      "type": "area",
      "zones": [
        {
          "zoneId": 29,
          "name": "Zone 29",
          "type": "zone",
          "communities": [
            {
              "name": "Bisset",
              "type": "community",
              "area": "South East",
              "zone": 29,
              "code": 188703,
            },
            {
              "name": "Crawford Plains",
              "type": "community",
              "area": "South East",
              "zone": 29,
              "code": 189003,
            },
            {
              "name": "Daly Grove",
              "type": "community",
              "area": "South East",
              "zone": 29,
              "code": 189002,
            },
            {
              "name": "Ekota",
              "type": "community",
              "area": "South East",
              "zone": 29,
              "code": 188802,
            },
            {
              "name": "Greenview_EDMO",
              "type": "community",
              "area": "South East",
              "zone": 29,
              "code": 188301,
            },
            {
              "name": "Hillview",
              "type": "community",
              "area": "South East",
              "zone": 29,
              "code": 188302,
            },
            {
              "name": "Jackson Heights",
              "type": "community",
              "area": "South East",
              "zone": 29,
              "code": 188401,
            },
            {
              "name": "Kameyosek",
              "type": "community",
              "area": "South East",
              "zone": 29,
              "code": 188502,
            },
            {
              "name": "Kiniski Gardens",
              "type": "community",
              "area": "South East",
              "zone": 29,
              "code": 188402,
            },
            {
              "name": "Lee Ridge",
              "type": "community",
              "area": "South East",
              "zone": 29,
              "code": 188204,
            },
            {
              "name": "Menisa",
              "type": "community",
              "area": "South East",
              "zone": 29,
              "code": 188803,
            },
            {
              "name": "Meyokumin",
              "type": "community",
              "area": "South East",
              "zone": 29,
              "code": 188901,
            },
            {
              "name": "Meyonohk",
              "type": "community",
              "area": "South East",
              "zone": 29,
              "code": 188503,
            },
            {
              "name": "Michaels Park",
              "type": "community",
              "area": "South East",
              "zone": 29,
              "code": 188202,
            },
            {
              "name": "Mill Woods Park",
              "type": "community",
              "area": "South East",
              "zone": 29,
              "code": 188504,
            },
            {
              "name": "Mill Woods Town Centre",
              "type": "community",
              "area": "South East",
              "zone": 29,
              "code": 188602,
            },
            {
              "name": "Minchau",
              "type": "community",
              "area": "South East",
              "zone": 29,
              "code": 188701,
            },
            {
              "name": "Pollard Meadows",
              "type": "community",
              "area": "South East",
              "zone": 29,
              "code": 189001,
            },
            {
              "name": "Richfield",
              "type": "community",
              "area": "South East",
              "zone": 29,
              "code": 188203,
            },
            {
              "name": "Sakaw",
              "type": "community",
              "area": "South East",
              "zone": 29,
              "code": 188902,
            },
            {
              "name": "Satoo",
              "type": "community",
              "area": "South East",
              "zone": 29,
              "code": 188801,
            },
            {
              "name": "Tawa",
              "type": "community",
              "area": "South East",
              "zone": 29,
              "code": 188601,
            },
            {
              "name": "Tipaskan",
              "type": "community",
              "area": "South East",
              "zone": 29,
              "code": 188501,
            },
            {
              "name": "Tweddle Place",
              "type": "community",
              "area": "South East",
              "zone": 29,
              "code": 188201,
            },
            {
              "name": "Weinlos",
              "type": "community",
              "area": "South East",
              "zone": 29,
              "code": 188702,
            },
          ],
        },
        {
          "zoneId": 30,
          "name": "Zone 30",
          "type": "zone",
          "communities": [
            {
              "name": "Larkspur",
              "type": "community",
              "area": "South East",
              "zone": 30,
              "code": 102908,
            },
            {
              "name": "Laurel",
              "type": "community",
              "area": "South East",
              "zone": 30,
              "code": 190600,
            },
            {
              "name": "Maple",
              "type": "community",
              "area": "South East",
              "zone": 30,
              "code": 190500,
            },
            {
              "name": "Meadows Area",
              "type": "community",
              "area": "South East",
              "zone": 30,
              "code": 190000,
            },
            {
              "name": "Silver Berry",
              "type": "community",
              "area": "South East",
              "zone": 30,
              "code": 190200,
            },
            {
              "name": "Tamarack",
              "type": "community",
              "area": "South East",
              "zone": 30,
              "code": 190400,
            },
            {
              "name": "Wild Rose",
              "type": "community",
              "area": "South East",
              "zone": 30,
              "code": 190100,
            },
          ],
        },
        {
          "zoneId": 41,
          "name": "Zone 41",
          "type": "zone",
          "communities": [
            {
              "name": "Calgary Trail North",
              "type": "community",
              "area": "South East",
              "zone": 41,
              "code": 185110,
            },
            {
              "name": "Calgary Trail South",
              "type": "community",
              "area": "South East",
              "zone": 41,
              "code": 185120,
            },
            {
              "name": "CPR Irvine",
              "type": "community",
              "area": "South East",
              "zone": 41,
              "code": 410100,
            },
            {
              "name": "South Edmonton Common",
              "type": "community",
              "area": "South East",
              "zone": 41,
              "code": 185140,
            },
            {
              "name": "Strathcona Industrial Park",
              "type": "community",
              "area": "South East",
              "zone": 41,
              "code": 185400,
            },
          ],
        },
        {
          "zoneId": 42,
          "name": "Zone 42",
          "type": "zone",
          "communities": [
            {
              "name": "Eastgate Business Park",
              "type": "community",
              "area": "South East",
              "zone": 42,
              "code": 186400,
            },
            {
              "name": "Maple Ridge_EDMO",
              "type": "community",
              "area": "South East",
              "zone": 42,
              "code": 187800,
            },
          ],
        },
        {
          "zoneId": 53,
          "name": "Zone 53",
          "type": "zone",
          "communities": [
            {
              "name": "Charlesworth",
              "type": "community",
              "area": "South East",
              "zone": 53,
              "code": 530400,
            },
            {
              "name": "Ellerslie",
              "type": "community",
              "area": "South East",
              "zone": 53,
              "code": 530100,
            },
            {
              "name": "Rural South East",
              "type": "community",
              "area": "South East",
              "zone": 53,
              "code": 530000,
            },
            {
              "name": "Summerside",
              "type": "community",
              "area": "South East",
              "zone": 53,
              "code": 530200,
            },
            {
              "name": "Walker",
              "type": "community",
              "area": "South East",
              "zone": 53,
              "code": 530500,
            },
          ],
        },
      ],
    },
  ],
  "communities": [
    {
      "name": "Alberta Park Industrial",
      "type": "community",
    },
    {
      "name": "Anthony Henday Sountheast",
      "type": "community",
    },
    {
      "name": "Armstrong Industrial",
      "type": "community",
    },
    {
      "name": "Bearspaw_Edmo",
      "type": "community",
    },
    {
      "name": "Bonaventure Industrial",
      "type": "community",
    },
    {
      "name": "Brown Industrial",
      "type": "community",
    },
    {
      "name": "Carleton Square Industrial",
      "type": "community",
    },
    {
      "name": "Chapelle Area",
      "type": "community",
    },
    {
      "name": "Cold Lake North",
      "type": "community",
    },
    {
      "name": "Coronet Addition Industrial",
      "type": "community",
    },
    {
      "name": "Coronet Industrial",
      "type": "community",
    },
    {
      "name": "CPR West",
      "type": "community",
    },
    {
      "name": "Crystallina Nera",
      "type": "community",
    },
    {
      "name": "Davies Industrial East",
      "type": "community",
    },
    {
      "name": "Davies Industrial West",
      "type": "community",
    },
    {
      "name": "Desrochers Area",
      "type": "community",
    },
    {
      "name": "Dominion Industrial",
      "type": "community",
    },
    {
      "name": "Ebbers Industrial",
      "type": "community",
    },
    {
      "name": "Edgemont",
      "type": "community",
    },
    {
      "name": "Edmiston Industrial",
      "type": "community",
    },
    {
      "name": "Edmonton Municipal Airport",
      "type": "community",
    },
    {
      "name": "Edmonton Research and Develpoment Park",
      "type": "community",
    },
    {
      "name": "Ellerslie Industrial Area",
      "type": "community",
    },
    {
      "name": "Gagnon Estate Industrial",
      "type": "community",
    },
    {
      "name": "Gainer Industrial",
      "type": "community",
    },
    {
      "name": "Garside Industrial",
      "type": "community",
    },
    {
      "name": "Girard Industrial",
      "type": "community",
    },
    {
      "name": "Gorman Industrial",
      "type": "community",
    },
    {
      "name": "Granville",
      "type": "community",
    },
    {
      "name": "Hagmann Estates Industrial",
      "type": "community",
    },
    {
      "name": "The Hamptons",
      "type": "community",
    },
    {
      "name": "Hawin Park Estate Industrial",
      "type": "community",
    },
    {
      "name": "High Park Industrial",
      "type": "community",
    },
    {
      "name": "Huff Bremner Estates Industrial",
      "type": "community",
    },
    {
      "name": "Kennedale Industrial",
      "type": "community",
    },
    {
      "name": "Lake District North East Portion",
      "type": "community",
    },
    {
      "name": "Lambton Industrial",
      "type": "community",
    },
    {
      "name": "Lewis Farms Industrial",
      "type": "community",
    },
    {
      "name": "Macewan",
      "type": "community",
    },
    {
      "name": "Maple Ridge Industrial",
      "type": "community",
    },
    {
      "name": "McArthur Industrial",
      "type": "community",
    },
    {
      "name": "Mcintyre Industrial",
      "type": "community",
    },
    {
      "name": "McLeod",
      "type": "community",
    },
    {
      "name": "McNamara Industrial",
      "type": "community",
    },
    {
      "name": "Mistatim Industrial",
      "type": "community",
    },
    {
      "name": "Mitchell Industrial",
      "type": "community",
    },
    {
      "name": "Morin Industrial",
      "type": "community",
    },
    {
      "name": "Morris Industrial",
      "type": "community",
    },
    {
      "name": "Norwester Industrial",
      "type": "community",
    },
    {
      "name": "Papaschase Industrial",
      "type": "community",
    },
    {
      "name": "Parsons Industrial",
      "type": "community",
    },
    {
      "name": "Pilot Sound Area West Portion",
      "type": "community",
    },
    {
      "name": "Place La rue",
      "type": "community",
    },
    {
      "name": "Poundmaker Indusstrial",
      "type": "community",
    },
    {
      "name": "Pylypow Industrial",
      "type": "community",
    },
    {
      "name": "Rampart Industrial",
      "type": "community",
    },
    {
      "name": "Rossdale Industrial",
      "type": "community",
    },
    {
      "name": "Rural North East North Sturgeon",
      "type": "community",
    },
    {
      "name": "Rural North West",
      "type": "community",
    },
    {
      "name": "Rural West",
      "type": "community",
    },
    {
      "name": "Rural West Lewis Farms",
      "type": "community",
    },
    {
      "name": "Sheffield Industrial",
      "type": "community",
    },
    {
      "name": "Southeast Industrial",
      "type": "community",
    },
    {
      "name": "Stone Industrial",
      "type": "community",
    },
    {
      "name": "Sunwapta Industrial",
      "type": "community",
    },
    {
      "name": "Terwillegar Area",
      "type": "community",
    },
    {
      "name": "The Orchards At Ellersile",
      "type": "community",
    },
    {
      "name": "University of Alberta ",
      "type": "community",
    },
    {
      "name": "University of Alberta Farm",
      "type": "community",
    },
    {
      "name": "Vegreville",
      "type": "community",
    },
    {
      "name": "Wedgewood Heights ",
      "type": "community",
    },
    {
      "name": "Weir Industrial",
      "type": "community",
    },
    {
      "name": "West Sheffield Industrial",
      "type": "community",
    },
    {
      "name": "Westview Village ",
      "type": "community",
    },
    {
      "name": "Wetaskiwin",
      "type": "community",
    },
    {
      "name": "White Industrial",
      "type": "community",
    },
    {
      "name": "Wilson Industrial",
      "type": "community",
    },
    {
      "name": "Winterburn Industrial Area East",
      "type": "community",
    },
    {
      "name": "Winterburn Industrial Area West",
      "type": "community",
    },
    {
      "name": "Youngstown Industrial",
      "type": "community",
    },
  ],
  "mds": [
    {
      "name": "Rural Athabasca County",
      "type": "md",
    },
    {
      "name": "Rural Barrhead County",
      "type": "md",
    },
    {
      "name": "Rural Beaver County",
      "type": "md",
    },
    {
      "name": "Rural Bonnyville M.D.",
      "type": "md",
    },
    {
      "name": "Rural Brazeau County",
      "type": "md",
    },
    {
      "name": "Rural Lac Ste. Anne County",
      "type": "md",
    },
    {
      "name": "Rural Lamont County",
      "type": "md",
    },
    {
      "name": "Rural Leduc County",
      "type": "md",
    },
    {
      "name": "Rural Parkland County",
      "type": "md",
    },
    {
      "name": "Rural Smoky Lake County",
      "type": "md",
    },
    {
      "name": "Rural St. Paul County",
      "type": "md",
    },
    {
      "name": "Rural Strathcona County",
      "type": "md",
    },
    {
      "name": "Rural Sturgeon County",
      "type": "md",
    },
    {
      "name": "Rural Thorhild County",
      "type": "md",
    },
    {
      "name": "Rural Westlock County",
      "type": "md",
    },
    {
      "name": "Rural Wetaskiwin County",
      "type": "md",
    },
  ],
}
