module.exports = {
  "cities": [
    {
      "name": "Barrhead",
    },
    {
      "name": "Beaumont",
    },
    {
      "name": "Bon Accord",
    },
    {
      "name": "Bonnyville Town",
    },
    {
      "name": "Bruderheim",
    },
    {
      "name": "Calmar",
    },
    {
      "name": "Camrose",
    },
    {
      "name": "Cold Lake",
    },
    {
      "name": "Devon",
    },
    {
      "name": "Drayton Valley",
    },
    {
      "name": "Edmonton",
    },
    {
      "name": "Elk Point",
    },
    {
      "name": "Fort Saskatchewan",
    },
    {
      "name": "Gibbons",
    },
    {
      "name": "Lake",
    },
    {
      "name": "Lamont",
    },
    {
      "name": "Leduc",
    },
    {
      "name": "Legal",
    },
    {
      "name": "Millet",
    },
    {
      "name": "Morinville",
    },
    {
      "name": "Mundare",
    },
    {
      "name": "Onoway",
    },
    {
      "name": "Redwater",
    },
    {
      "name": "Sherwood Park",
    },
    {
      "name": "Spruce Grove",
    },
    {
      "name": "St. Albert",
    },
    {
      "name": "St. Paul Town",
    },
    {
      "name": "Stony Plain",
    },
    {
      "name": "Thorsby",
    },
    {
      "name": "Toname",
    },
    {
      "name": "Vegreville",
    },
    {
      "name": "West Lock",
    },
    {
      "name": "Wetaskiwin",
    },
  ],
  "mds": [
    {
      "name": "Rural Athabasca County",
    },
    {
      "name": "Rural Barrhead County",
    },
    {
      "name": "Rural Beaver County",
    },
    {
      "name": "Rural Bonnyville M.D.",
    },
    {
      "name": "Rural Brazeau County",
    },
    {
      "name": "Rural Lac Ste. Anne County",
    },
    {
      "name": "Rural Lamont County",
    },
    {
      "name": "Rural Leduc County",
    },
    {
      "name": "Rural Parkland County",
    },
    {
      "name": "Rural Smoky Lake County",
    },
    {
      "name": "Rural St. Paul County",
    },
    {
      "name": "Rural Strathcona County",
    },
    {
      "name": "Rural Sturgeon County",
    },
    {
      "name": "Rural Thorhild County",
    },
    {
      "name": "Rural Westlock County",
    },
    {
      "name": "Rural Wetaskiwin County",
    },
  ],
  "communities": [
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "Abbottsfield",
      "zone": 23,
      "code": 107800,
    },
    {
      "name": "Akinsdale",
      "city": "St Albert",
    },
    {
      "city": "Edmonton",
      "area": "North West",
      "name": "Albany",
      "zone": 27,
      "code": 302,
    },
    {
      "city": "Edmonton",
      "area": "Central",
      "name": "Alberta Avenue",
      "zone": 5,
      "code": 103300,
    },
    {
      "name": "Alberta Park Industrial",
      "city": "Edmonton",
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "Aldergrove",
      "zone": 20,
      "code": 3903,
    },
    {
      "name": "Alexandra Park",
      "city": "Leduc",
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Allard",
      "zone": 55,
      "code": 550800,
    },
    {
      "city": "Edmonton",
      "area": "South Central",
      "name": "Allendale",
      "zone": 15,
      "code": 205900,
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Ambleside",
      "zone": 56,
      "code": 560200,
    },
    {
      "city": "Edmonton",
      "area": "North West",
      "name": "Anthony Henday",
      "zone": 40,
      "code": 32904,
    },
    {
      "city": "Edmonton",
      "area": "North West",
      "name": "Anthony Henday Big Lake",
      "zone": 40,
      "code": 32908,
    },
    {
      "city": "Edmonton",
      "area": "North West",
      "name": "Anthony Henday Castledowns",
      "zone": 27,
      "code": 303,
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "Anthony Henday Clareview",
      "zone": 35,
      "code": 103005,
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "Anthony Henday Horse Hill",
      "zone": 3,
      "code": 103107,
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "Anthony Henday Lake District",
      "zone": 28,
      "code": 100011,
    },
    {
      "city": "Edmonton",
      "area": "North West",
      "name": "Anthony Henday Mistatim",
      "zone": 40,
      "code": 32907,
    },
    {
      "name": "Anthony Henday Sountheast",
      "city": "Edmonton",
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Anthony Henday South",
      "zone": 16,
      "code": 206400,
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "Anthony Henday South West",
      "zone": 20,
      "code": 4309,
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Anthony Henday Terwillegar",
      "zone": 14,
      "code": 202102,
    },
    {
      "city": "Edmonton",
      "area": "South Central",
      "name": "Argyll",
      "zone": 17,
      "code": 184800,
    },
    {
      "name": "Armstrong Industrial",
      "city": "Edmonton",
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Aspen Gardens",
      "zone": 16,
      "code": 200901,
    },
    {
      "name": "Aspen Glen",
      "city": "Spruce Grove",
    },
    {
      "city": "Edmonton",
      "area": "North West",
      "name": "Athlone",
      "zone": 1,
      "code": 1400,
    },
    {
      "city": "Edmonton",
      "area": "South Central",
      "name": "Avonmore",
      "zone": 17,
      "code": 184900,
    },
    {
      "name": "Baileys Subdivision",
      "city": "Sherwood Park",
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "Balwin",
      "zone": 2,
      "code": 102000,
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "Bannerman",
      "zone": 35,
      "code": 102904,
    },
    {
      "city": "Edmonton",
      "area": "North West",
      "name": "Baranow",
      "zone": 27,
      "code": 110,
    },
    {
      "city": "Edmonton",
      "area": "North West",
      "name": "Baturyn",
      "zone": 27,
      "code": 201,
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "Beacon Heights",
      "zone": 23,
      "code": 107600,
    },
    {
      "name": "Bearspaw_Edmo",
      "city": "Edmonton",
    },
    {
      "name": "Beau Val",
      "city": "Beaumont",
    },
    {
      "city": "Edmonton",
      "area": "North West",
      "name": "Beaumaris",
      "zone": 27,
      "code": 203,
    },
    // {
    //   "name": "Beaumont",
    //   "city": "Beaumont",
    // },
    {
      "name": "Beaumont Lakes",
      "city": "Beaumont",
    },
    {
      "city": "Edmonton",
      "area": "South Central",
      "name": "Belgravia",
      "zone": 15,
      "code": 200300,
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "Belle Rive",
      "zone": 28,
      "code": 100007,
    },
    {
      "city": "Edmonton",
      "area": "Central",
      "name": "Bellevue",
      "zone": 9,
      "code": 106200,
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "Belmead",
      "zone": 20,
      "code": 3902,
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "Belmont",
      "zone": 35,
      "code": 102906,
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "Belvedere",
      "zone": 2,
      "code": 101400,
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "Bergman",
      "zone": 23,
      "code": 107500,
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "Beverly Heights",
      "zone": 23,
      "code": 107900,
    },
    {
      "city": "Edmonton",
      "area": "South East",
      "name": "Bisset",
      "zone": 29,
      "code": 188703,
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Blackburne",
      "zone": 55,
      "code": 550100,
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Blackmud Creek",
      "zone": 55,
      "code": 550200,
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Blackmud Creek Ravine",
      "zone": 55,
      "code": 551400,
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Blue Quill",
      "zone": 16,
      "code": 201002,
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Blue Quill Estates",
      "zone": 16,
      "code": 201003,
    },
    {
      "name": "Bonaventure Industrial",
      "city": "Edmonton",
    },
    {
      "city": "Edmonton",
      "area": "South Central",
      "name": "Bonnie Doon",
      "zone": 18,
      "code": 182500,
    },
    {
      "city": "Edmonton",
      "area": "Central",
      "name": "Boyle Street",
      "zone": 13,
      "code": 109500,
    },
    {
      "name": "Braeside",
      "city": "St Albert",
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Brander Gardens",
      "zone": 14,
      "code": 200401,
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "Breckenridge Greens",
      "zone": 58,
      "code": 580100,
    },
    {
      "name": "Brentwood_CSTS",
      "city": "Sherwood Park",
    },
    {
      "name": "Bridgeport",
      "city": "Leduc",
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "Brintnell",
      "zone": 3,
      "code": 103104,
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "Britannia Youngstown",
      "zone": 21,
      "code": 5400,
    },
    {
      "name": "Broadmoor",
      "city": "Sherwood Park",
    },
    {
      "name": "Broadmoor Estates",
      "city": "Sherwood Park",
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Brookside",
      "zone": 14,
      "code": 200402,
    },
    {
      "name": "Brookside_BEAU",
      "city": "Beaumont",
    },
    {
      "name": "Brookview",
      "city": "Stony Plain",
    },
    {
      "name": "Brookwood",
      "city": "Spruce Grove",
    },
    {
      "name": "Brown Industrial",
      "city": "Edmonton",
    },
    {
      "name": "Broxton Park",
      "city": "Spruce Grove",
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Bulyea Heights",
      "zone": 14,
      "code": 200405,
    },
    {
      "city": "Edmonton",
      "area": "North West",
      "name": "Caernarvon",
      "zone": 27,
      "code": 102,
    },
    {
      "city": "Edmonton",
      "area": "North West",
      "name": "Calder",
      "zone": 1,
      "code": 1500,
    },
    {
      "name": "Caledonia",
      "city": "Leduc",
    },
    {
      "city": "Edmonton",
      "area": "South East",
      "name": "Calgary Trail North",
      "zone": 41,
      "code": 185110,
    },
    {
      "city": "Edmonton",
      "area": "South East",
      "name": "Calgary Trail South",
      "zone": 41,
      "code": 185120,
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Callaghan",
      "zone": 55,
      "code": 550700,
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "Callingwood North",
      "zone": 20,
      "code": 4201,
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "Callingwood South",
      "zone": 20,
      "code": 4202,
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "Cameron Heights_EDMO",
      "zone": 20,
      "code": 4306,
    },
    {
      "name": "Campbell Business Park",
      "city": "St Albert",
    },
    {
      "name": "Campbelltown Heights",
      "city": "Sherwood Park",
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "Canon Ridge",
      "zone": 35,
      "code": 103003,
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "Canora",
      "zone": 21,
      "code": 5600,
    },
    {
      "city": "Edmonton",
      "area": "North West",
      "name": "Canossa",
      "zone": 27,
      "code": 104,
    },
    {
      "city": "Edmonton",
      "area": "South Central",
      "name": "Capilano",
      "zone": 19,
      "code": 180501,
    },
    {
      "name": "Carleton Square Industrial",
      "city": "Edmonton",
    },
    {
      "city": "Edmonton",
      "area": "North West",
      "name": "Carlisle",
      "zone": 27,
      "code": 103,
    },
    {
      "city": "Edmonton",
      "area": "North West",
      "name": "Carlton",
      "zone": 27,
      "code": 206,
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Carter Crest",
      "zone": 14,
      "code": 200408,
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Cashman",
      "zone": 55,
      "code": 552000,
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "Casselman",
      "zone": 2,
      "code": 101103,
    },
    {
      "name": "Central Business District",
      "city": "Leduc",
    },
    {
      "city": "Edmonton",
      "area": "Central",
      "name": "Central McDougall",
      "zone": 8,
      "code": 3604,
    },
    {
      "name": "Centre In The Park",
      "city": "Sherwood Park",
    },
    {
      "name": "Chaleureuse Business Park",
      "city": "Beaumont",
    },
    {
      "city": "Edmonton",
      "area": "North West",
      "name": "Chambery",
      "zone": 27,
      "code": 106,
    },
    {
      "name": "Chapelle Area",
      "city": "Edmonton",
    },
    {
      "city": "Edmonton",
      "area": "South East",
      "name": "Charlesworth",
      "zone": 53,
      "code": 530400,
    },
    {
      "name": "Charlton Heights",
      "city": "Spruce Grove",
    },
    {
      "name": "Chelsea Heights",
      "city": "Sherwood Park",
    },
    {
      "name": "Citadel Ridge",
      "city": "Beaumont",
    },
    {
      "name": "City Centre",
      "city": "Spruce Grove",
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "Clareview Town Centre",
      "zone": 35,
      "code": 102909,
    },
    {
      "name": "Clarkdale Meadows",
      "city": "Sherwood Park",
    },
    {
      "name": "Clover Bar Ranch",
      "city": "Sherwood Park",
    },
    {
      "name": "Clover Park Fort Sask.",
      "city": "Fort Saskatchewan",
    },
    {
      "city": "Edmonton",
      "area": "South Central",
      "name": "Cloverdale",
      "zone": 18,
      "code": 181100,
    },
    {
      "name": "Cold Lake North",
      "city": "Edmonton",
    },
    {
      "name": "Coloniale Estates_BEAU",
      "city": "Beaumont",
    },
    {
      "name": "Corinthia Park",
      "city": "Leduc",
    },
    {
      "name": "Coronet Addition Industrial",
      "city": "Edmonton",
    },
    {
      "name": "Coronet Industrial",
      "city": "Edmonton",
    },
    {
      "name": "Country Club Estates",
      "city": "Sherwood Park",
    },
    {
      "name": "Country Plains Estates",
      "city": "Stony Plain",
    },
    {
      "city": "Edmonton",
      "area": "South East",
      "name": "CPR Irvine",
      "zone": 41,
      "code": 410100,
    },
    {
      "name": "CPR West",
      "city": "Edmonton",
    },
    {
      "name": "Craigavon",
      "city": "Sherwood Park",
    },
    {
      "city": "Edmonton",
      "area": "South East",
      "name": "Crawford Plains",
      "zone": 29,
      "code": 189003,
    },
    {
      "name": "Creekside",
      "city": "Spruce Grove",
    },
    {
      "name": "Creekside Point",
      "city": "Stony Plain",
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "Crestwood",
      "zone": 10,
      "code": 7900,
    },
    {
      "city": "Edmonton",
      "area": "Central",
      "name": "Cromdale",
      "zone": 9,
      "code": 105900,
    },
    {
      "name": "Crystallina Nera",
      "city": "Edmonton",
    },
    {
      "city": "Edmonton",
      "area": "North West",
      "name": "Cumberland",
      "zone": 27,
      "code": 108,
    },
    {
      "city": "Edmonton",
      "area": "South East",
      "name": "Daly Grove",
      "zone": 29,
      "code": 189002,
    },
    {
      "name": "Dansereau Meadows",
      "city": "Beaumont",
    },
    {
      "name": "Davidson Creek",
      "city": "Sherwood Park",
    },
    {
      "name": "Davies Industrial East",
      "city": "Edmonton",
    },
    {
      "name": "Davies Industrial West",
      "city": "Edmonton",
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "Dechene",
      "zone": 20,
      "code": 4302,
    },
    {
      "name": "Deer Park_SPGR",
      "city": "Spruce Grove",
    },
    {
      "name": "Deer Ridge_SALB",
      "city": "St Albert",
    },
    {
      "name": "Deer Valley",
      "city": "Leduc",
    },
    {
      "city": "Edmonton",
      "area": "Central",
      "name": "Delton",
      "zone": 5,
      "code": 103700,
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "Delwood",
      "zone": 2,
      "code": 101300,
    },
    {
      "name": "Desrochers Area",
      "city": "Edmonton",
    },
    {
      "name": "Diamond Industrial Park",
      "city": "Spruce Grove",
    },
    {
      "name": "Dominion Industrial",
      "city": "Edmonton",
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "Donsdale",
      "zone": 20,
      "code": 4305,
    },
    {
      "city": "Edmonton",
      "area": "Central",
      "name": "Dovercourt",
      "zone": 4,
      "code": 2100,
    },
    {
      "name": "Downtown Spruce Grove",
      "city": "Spruce Grove",
    },
    {
      "city": "Edmonton",
      "area": "Central",
      "name": "Downtown_EDMO",
      "zone": 12,
      "code": 3606,
    },
    {
      "name": "Downtown_SALB",
      "city": "St Albert",
    },
    {
      "name": "Downtown_STPL",
      "city": "Stony Plain",
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Duggan",
      "zone": 16,
      "code": 206001,
    },
    {
      "city": "Edmonton",
      "area": "North West",
      "name": "Dunluce",
      "zone": 27,
      "code": 101,
    },
    {
      "name": "Durham Town Square",
      "city": "Sherwood Park",
    },
    {
      "name": "Eaglemont Heights",
      "city": "Beaumont",
    },
    {
      "city": "Edmonton",
      "area": "South East",
      "name": "Eastgate Business Park",
      "zone": 42,
      "code": 186400,
    },
    {
      "city": "Edmonton",
      "area": "Central",
      "name": "Eastwood",
      "zone": 5,
      "code": 104800,
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "Eaux Claires",
      "zone": 28,
      "code": 100006,
    },
    {
      "name": "Ebbers Industrial",
      "city": "Edmonton",
    },
    {
      "name": "Edgeland Park",
      "city": "Stony Plain",
    },
    {
      "name": "Edgemont",
      "city": "Edmonton",
    },
    {
      "name": "Edmiston Industrial",
      "city": "Edmonton",
    },
    {
      "name": "Edmonton Municipal Airport",
      "city": "Edmonton",
    },
    {
      "city": "Edmonton",
      "area": "Central",
      "name": "Edmonton Northlands",
      "zone": 9,
      "code": 106600,
    },
    {
      "name": "Edmonton Research and Develpoment Park",
      "city": "Edmonton",
    },
    {
      "city": "Edmonton",
      "area": "South East",
      "name": "Ekota",
      "zone": 29,
      "code": 188802,
    },
    {
      "city": "Edmonton",
      "area": "South East",
      "name": "Ellerslie",
      "zone": 53,
      "code": 530100,
    },
    {
      "name": "Ellerslie Industrial Area",
      "city": "Edmonton",
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "Elmwood",
      "zone": 22,
      "code": 6600,
    },
    {
      "city": "Edmonton",
      "area": "Central",
      "name": "Elmwood Park",
      "zone": 5,
      "code": 104700,
    },
    {
      "city": "Edmonton",
      "area": "North West",
      "name": "Elsinore",
      "zone": 27,
      "code": 204,
    },
    {
      "name": "Emerald Hills",
      "city": "Sherwood Park",
    },
    {
      "city": "Edmonton",
      "area": "South Central",
      "name": "Empire Park",
      "zone": 15,
      "code": 183700,
    },
    {
      "name": "Erin Ridge",
      "city": "St Albert",
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Ermineskin",
      "zone": 16,
      "code": 206102,
    },
    {
      "name": "Estates of Sherwood",
      "city": "Sherwood Park",
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "Evansdale",
      "zone": 2,
      "code": 100901,
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "Evergreen_EDMO",
      "zone": 51,
      "code": 510300,
    },
    {
      "name": "Executive Estates",
      "city": "Sherwood Park",
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Falconer Heights",
      "zone": 14,
      "code": 200407,
    },
    {
      "name": "Fieldstone",
      "city": "Spruce Grove",
    },
    {
      "name": "Folkstone Place",
      "city": "Stony Plain",
    },
    {
      "name": "Forest Green_STPL",
      "city": "Stony Plain",
    },
    {
      "name": "Forest Heights",
      "city": "Beaumont",
    },
    {
      "city": "Edmonton",
      "area": "South Central",
      "name": "Forest Heights_EDMO",
      "zone": 19,
      "code": 180100,
    },
    {
      "name": "Forest Lawn_SALB",
      "city": "St Albert",
    },
    {
      "name": "Fountain Creek Estates",
      "city": "Sherwood Park",
    },
    {
      "name": "Four Season Estates_BEAU",
      "city": "Beaumont",
    },
    {
      "name": "Foxboro",
      "city": "Sherwood Park",
    },
    {
      "name": "Foxhaven",
      "city": "Sherwood Park",
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "Fraser",
      "zone": 35,
      "code": 102902,
    },
    {
      "city": "Edmonton",
      "area": "South Central",
      "name": "Fulton Place",
      "zone": 19,
      "code": 180502,
    },
    {
      "name": "Gagnon Estate Industrial",
      "city": "Edmonton",
    },
    {
      "name": "Gainer Industrial",
      "city": "Edmonton",
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "Gariepy",
      "zone": 20,
      "code": 4303,
    },
    {
      "city": "Edmonton",
      "area": "South Central",
      "name": "Garneau",
      "zone": 15,
      "code": 205000,
    },
    {
      "name": "Garside Industrial",
      "city": "Edmonton",
    },
    {
      "name": "Genesis On The Lakes",
      "city": "Stony Plain",
    },
    {
      "name": "Girard Industrial",
      "city": "Edmonton",
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "Glastonbury",
      "zone": 58,
      "code": 580200,
    },
    {
      "name": "Glen Allan",
      "city": "Sherwood Park",
    },
    {
      "name": "Glenbrae Meadows",
      "city": "Beaumont",
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "Glengarry",
      "zone": 2,
      "code": 101200,
    },
    {
      "city": "Edmonton",
      "area": "Central",
      "name": "Glenora",
      "zone": 11,
      "code": 8600,
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Glenridding Area",
      "zone": 56,
      "code": 560500,
    },
    {
      "name": "Glens The",
      "city": "Stony Plain",
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "Glenwood",
      "zone": 22,
      "code": 5900,
    },
    {
      "city": "Edmonton",
      "area": "South Central",
      "name": "Gold Bar",
      "zone": 19,
      "code": 180503,
    },
    {
      "city": "Edmonton",
      "area": "North West",
      "name": "Goodridge Corners",
      "zone": 27,
      "code": 111,
    },
    {
      "name": "Gorman Industrial",
      "city": "Edmonton",
    },
    {
      "name": "Goudreau Terrace",
      "city": "Beaumont",
    },
    {
      "name": "Grandin",
      "city": "St Albert",
    },
    {
      "city": "Edmonton",
      "area": "South Central",
      "name": "Grandview Heights_EDMO",
      "zone": 15,
      "code": 200501,
    },
    {
      "name": "Granville",
      "city": "Edmonton",
    },
    {
      "name": "Graybriar",
      "city": "Stony Plain",
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Greenfield",
      "zone": 16,
      "code": 200903,
    },
    {
      "city": "Edmonton",
      "area": "South East",
      "name": "Greenview_EDMO",
      "zone": 29,
      "code": 188301,
    },
    {
      "city": "Edmonton",
      "area": "North West",
      "name": "Griesbach",
      "zone": 27,
      "code": 112,
    },
    {
      "name": "Grove Meadows",
      "city": "Spruce Grove",
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "Grovenor",
      "zone": 21,
      "code": 3300,
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Haddow",
      "zone": 14,
      "code": 202101,
    },
    {
      "name": "Hagmann Estates Industrial",
      "city": "Edmonton",
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "Hairsine",
      "zone": 35,
      "code": 102903,
    },
    {
      "name": "The Hamptons",
      "city": "Edmonton",
    },
    {
      "name": "Harvest Ridge",
      "city": "Spruce Grove",
    },
    {
      "name": "Hawin Park Estate Industrial",
      "city": "Edmonton",
    },
    {
      "city": "Edmonton",
      "area": "North West",
      "name": "Hawks Ridge",
      "zone": 59,
      "code": 590500,
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Hays Ridge Area",
      "zone": 55,
      "code": 551300,
    },
    {
      "city": "Edmonton",
      "area": "South Central",
      "name": "Hazeldean",
      "zone": 17,
      "code": 184700,
    },
    {
      "name": "Heatherglen",
      "city": "Spruce Grove",
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Henderson Estates",
      "zone": 14,
      "code": 200406,
    },
    {
      "name": "Heritage Estates_STPL",
      "city": "Stony Plain",
    },
    {
      "name": "Heritage Hills",
      "city": "Sherwood Park",
    },
    {
      "name": "Heritage Lakes",
      "city": "St Albert",
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Heritage Valley Area",
      "zone": 55,
      "code": 550600,
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Heritage Valley Area East",
      "zone": 55,
      "code": 551200,
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Heritage Valley Town Centre Area",
      "zone": 55,
      "code": 551100,
    },
    {
      "name": "High Park Industrial",
      "city": "Edmonton",
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "High Park_EDMO",
      "zone": 21,
      "code": 5201,
    },
    {
      "name": "High Park_STPL",
      "city": "Stony Plain",
    },
    {
      "city": "Edmonton",
      "area": "Central",
      "name": "Highlands",
      "zone": 9,
      "code": 106500,
    },
    {
      "name": "Hilldowns",
      "city": "Spruce Grove",
    },
    {
      "name": "Hillsdale",
      "city": "Sherwood Park",
    },
    {
      "city": "Edmonton",
      "area": "South East",
      "name": "Hillview",
      "zone": 29,
      "code": 188302,
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Hodgson",
      "zone": 14,
      "code": 201102,
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "Hollick-Kenyon",
      "zone": 3,
      "code": 103102,
    },
    {
      "city": "Edmonton",
      "area": "South Central",
      "name": "Holyrood",
      "zone": 18,
      "code": 183100,
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "Homesteader",
      "zone": 35,
      "code": 103001,
    },
    {
      "name": "Homesteads",
      "city": "Stony Plain",
    },
    {
      "name": "Hubert Crescent",
      "city": "Sherwood Park",
    },
    {
      "city": "Edmonton",
      "area": "North West",
      "name": "Hudson",
      "zone": 27,
      "code": 205,
    },
    {
      "name": "Huff Bremner Estates Industrial",
      "city": "Edmonton",
    },
    {
      "city": "Edmonton",
      "area": "South Central",
      "name": "Idylwylde",
      "zone": 18,
      "code": 183300,
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "Industrial Heights",
      "zone": 6,
      "code": 105600,
    },
    {
      "city": "Edmonton",
      "area": "Central",
      "name": "Inglewood_EDMO",
      "zone": 7,
      "code": 3000,
    },
    {
      "name": "Inglewood_SALB",
      "city": "St Albert",
    },
    {
      "city": "Edmonton",
      "area": "South East",
      "name": "Jackson Heights",
      "zone": 29,
      "code": 188401,
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "Jamieson Place",
      "zone": 20,
      "code": 4301,
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "Jasper Park",
      "zone": 22,
      "code": 6400,
    },
    {
      "name": "Jutland Ridge",
      "city": "Stony Plain",
    },
    {
      "city": "Edmonton",
      "area": "South East",
      "name": "Kameyosek",
      "zone": 29,
      "code": 188502,
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Keheewin",
      "zone": 16,
      "code": 206202,
    },
    {
      "city": "Edmonton",
      "area": "South Central",
      "name": "Kenilworth",
      "zone": 18,
      "code": 183202,
    },
    {
      "name": "Kennedale Industrial",
      "city": "Edmonton",
    },
    {
      "city": "Edmonton",
      "area": "North West",
      "name": "Kensington",
      "zone": 1,
      "code": 1200,
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "Kernohan",
      "zone": 35,
      "code": 102907,
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Keswick Area",
      "zone": 56,
      "code": 560700,
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "Kildare",
      "zone": 2,
      "code": 101002,
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "Kilkenny",
      "zone": 2,
      "code": 101001,
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "Killarney",
      "zone": 2,
      "code": 101600,
    },
    {
      "city": "Edmonton",
      "area": "South Central",
      "name": "King Edward Park",
      "zone": 17,
      "code": 184100,
    },
    {
      "name": "Kingswood",
      "city": "St Albert",
    },
    {
      "city": "Edmonton",
      "area": "South East",
      "name": "Kiniski Gardens",
      "zone": 29,
      "code": 188402,
    },
    {
      "city": "Edmonton",
      "area": "North West",
      "name": "Kinokamau Plains Area",
      "zone": 40,
      "code": 32906,
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "Kirkness",
      "zone": 35,
      "code": 102901,
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "Klarvatten",
      "zone": 28,
      "code": 100002,
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "La Perle",
      "zone": 20,
      "code": 3901,
    },
    {
      "name": "Lacombe Park",
      "city": "St Albert",
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "Lago Lindo",
      "zone": 28,
      "code": 100001,
    },
    {
      "name": "Lake District North East Portion",
      "city": "Edmonton",
    },
    {
      "name": "Lake Westerra",
      "city": "Stony Plain",
    },
    {
      "name": "Lakeland Ridge",
      "city": "Sherwood Park",
    },
    {
      "name": "Lakeland Village",
      "city": "Sherwood Park",
    },
    {
      "name": "Lakeside Estates",
      "city": "Leduc",
    },
    {
      "name": "Lakeview",
      "city": "Stony Plain",
    },
    {
      "name": "Lakewood",
      "city": "Spruce Grove",
    },
    {
      "name": "Lambton Industrial",
      "city": "Edmonton",
    },
    {
      "city": "Edmonton",
      "area": "South Central",
      "name": "Lansdowne",
      "zone": 15,
      "code": 200600,
    },
    {
      "city": "Edmonton",
      "area": "South East",
      "name": "Larkspur",
      "zone": 30,
      "code": 102908,
    },
    {
      "city": "Edmonton",
      "area": "North West",
      "name": "Lauderdale",
      "zone": 1,
      "code": 1800,
    },
    {
      "city": "Edmonton",
      "area": "South East",
      "name": "Laurel",
      "zone": 30,
      "code": 190600,
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "Laurier Heights",
      "zone": 10,
      "code": 8200,
    },
    {
      "name": "Leduc Estates",
      "city": "Leduc",
    },
    {
      "city": "Edmonton",
      "area": "South East",
      "name": "Lee Ridge",
      "zone": 29,
      "code": 188204,
    },
    {
      "name": "Legacy Park",
      "city": "Spruce Grove",
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Leger",
      "zone": 14,
      "code": 200410,
    },
    {
      "city": "Edmonton",
      "area": "South Central",
      "name": "Lendrum Place",
      "zone": 15,
      "code": 200700,
    },
    {
      "name": "Lewis Farms Industrial",
      "city": "Edmonton",
    },
    {
      "name": "Linkside",
      "city": "Spruce Grove",
    },
    {
      "name": "Linsford Park",
      "city": "Leduc",
    },
    {
      "city": "Edmonton",
      "area": "North West",
      "name": "Lorelei",
      "zone": 27,
      "code": 202,
    },
    {
      "name": "Lorrelind",
      "city": "Sherwood Park",
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "Lymburn",
      "zone": 20,
      "code": 4101,
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "Lynnwood",
      "zone": 22,
      "code": 6700,
    },
    {
      "name": "Macewan",
      "city": "Edmonton",
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "MacTaggart",
      "zone": 14,
      "code": 140100,
    },
    {
      "name": "Madison Industrial Park",
      "city": "Spruce Grove",
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Magrath Heights",
      "zone": 14,
      "code": 140200,
    },
    {
      "city": "Edmonton",
      "area": "South Central",
      "name": "Malmo Plains",
      "zone": 15,
      "code": 200800,
    },
    {
      "city": "Edmonton",
      "area": "South East",
      "name": "Maple",
      "zone": 30,
      "code": 190500,
    },
    {
      "name": "Maple Ridge Industrial",
      "city": "Edmonton",
    },
    {
      "city": "Edmonton",
      "area": "South East",
      "name": "Maple Ridge_EDMO",
      "zone": 42,
      "code": 187800,
    },
    {
      "name": "Maplegrove",
      "city": "Sherwood Park",
    },
    {
      "name": "Maplewood",
      "city": "Sherwood Park",
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "Matt Berry",
      "zone": 3,
      "code": 103101,
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "Mayfield",
      "zone": 21,
      "code": 5100,
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "Mayliewan",
      "zone": 28,
      "code": 100008,
    },
    {
      "name": "McArthur Industrial",
      "city": "Edmonton",
    },
    {
      "city": "Edmonton",
      "area": "Central",
      "name": "McCauley",
      "zone": 13,
      "code": 109400,
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "McConachie Area",
      "zone": 3,
      "code": 103103,
    },
    {
      "name": "Mcintyre Industrial",
      "city": "Edmonton",
    },
    {
      "city": "Edmonton",
      "area": "South Central",
      "name": "McKernan",
      "zone": 15,
      "code": 205601,
    },
    {
      "name": "McLaughlin_SPGR",
      "city": "Spruce Grove",
    },
    {
      "name": "McLeod",
      "city": "Edmonton",
    },
    {
      "name": "McNamara Industrial",
      "city": "Edmonton",
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "McQueen",
      "zone": 21,
      "code": 3200,
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "Meadowlark Park_EDMO",
      "zone": 22,
      "code": 6200,
    },
    {
      "city": "Edmonton",
      "area": "South East",
      "name": "Meadows Area",
      "zone": 30,
      "code": 190000,
    },
    {
      "name": "Meadowview Park_LEDU",
      "city": "Leduc",
    },
    {
      "city": "Edmonton",
      "area": "South East",
      "name": "Menisa",
      "zone": 29,
      "code": 188803,
    },
    {
      "name": "Meridian Heights",
      "city": "Stony Plain",
    },
    {
      "name": "Meridian Meadows",
      "city": "Stony Plain",
    },
    {
      "city": "Edmonton",
      "area": "South East",
      "name": "Meyokumin",
      "zone": 29,
      "code": 188901,
    },
    {
      "city": "Edmonton",
      "area": "South East",
      "name": "Meyonohk",
      "zone": 29,
      "code": 188503,
    },
    {
      "city": "Edmonton",
      "area": "South East",
      "name": "Michaels Park",
      "zone": 29,
      "code": 188202,
    },
    {
      "city": "Edmonton",
      "area": "South Central",
      "name": "Mill Creek Ravine North",
      "zone": 15,
      "code": 184600,
    },
    {
      "city": "Edmonton",
      "area": "South Central",
      "name": "Mill Creek Ravine South",
      "zone": 17,
      "code": 184200,
    },
    {
      "city": "Edmonton",
      "area": "South East",
      "name": "Mill Woods Park",
      "zone": 29,
      "code": 188504,
    },
    {
      "city": "Edmonton",
      "area": "South East",
      "name": "Mill Woods Town Centre",
      "zone": 29,
      "code": 188602,
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "Miller",
      "zone": 2,
      "code": 101104,
    },
    {
      "name": "Millgrove",
      "city": "Spruce Grove",
    },
    {
      "name": "Mills Haven",
      "city": "Sherwood Park",
    },
    {
      "city": "Edmonton",
      "area": "South East",
      "name": "Minchau",
      "zone": 29,
      "code": 188701,
    },
    {
      "name": "Mission_SALB",
      "city": "St Albert",
    },
    {
      "name": "Mistatim Industrial",
      "city": "Edmonton",
    },
    {
      "name": "Mitchell Industrial",
      "city": "Edmonton",
    },
    {
      "name": "Montalet",
      "city": "Beaumont",
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "Montrose",
      "zone": 6,
      "code": 104600,
    },
    {
      "name": "Montrose Business Centre",
      "city": "Beaumont",
    },
    {
      "name": "Montrose Estates",
      "city": "Beaumont",
    },
    {
      "name": "Morin Industrial",
      "city": "Edmonton",
    },
    {
      "name": "Morris Industrial",
      "city": "Edmonton",
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "Newton",
      "zone": 6,
      "code": 105700,
    },
    {
      "name": "North Business Park",
      "city": "Stony Plain",
    },
    {
      "city": "Edmonton",
      "area": "Central",
      "name": "North Glenora",
      "zone": 7,
      "code": 3100,
    },
    {
      "name": "North Industrial",
      "city": "Stony Plain",
    },
    {
      "name": "North Ridge",
      "city": "St Albert",
    },
    {
      "name": "North Telford",
      "city": "Leduc",
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "Northmount",
      "zone": 2,
      "code": 100902,
    },
    {
      "name": "Northwest",
      "city": "Stony Plain",
    },
    {
      "name": "Norwester Industrial",
      "city": "Edmonton",
    },
    {
      "name": "Nottingham",
      "city": "Sherwood Park",
    },
    {
      "name": "Oakmont",
      "city": "St Albert",
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Ogilvie Ridge",
      "zone": 14,
      "code": 200409,
    },
    {
      "name": "Old Fort Saskatchewan",
      "city": "Fort Saskatchewan",
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "Oleskiw",
      "zone": 22,
      "code": 7300,
    },
    {
      "city": "Edmonton",
      "area": "Central",
      "name": "Oliver",
      "zone": 12,
      "code": 3605,
    },
    {
      "name": "Ordze Park",
      "city": "Sherwood Park",
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "Ormsby Place",
      "zone": 20,
      "code": 4102,
    },
    {
      "city": "Edmonton",
      "area": "South Central",
      "name": "Ottewell",
      "zone": 18,
      "code": 183600,
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "Overlanders",
      "zone": 35,
      "code": 103002,
    },
    {
      "city": "Edmonton",
      "area": "North West",
      "name": "Oxford",
      "zone": 27,
      "code": 107,
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "Ozerna",
      "zone": 28,
      "code": 100009,
    },
    {
      "name": "Papaschase Industrial",
      "city": "Edmonton",
    },
    {
      "city": "Edmonton",
      "area": "South Central",
      "name": "Parkallen_EDMO",
      "zone": 15,
      "code": 205600,
    },
    {
      "city": "Edmonton",
      "area": "Central",
      "name": "Parkdale_EDMO",
      "zone": 5,
      "code": 104300,
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "Parkview",
      "zone": 10,
      "code": 8000,
    },
    {
      "name": "Parsons Industrial",
      "city": "Edmonton",
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "Patricia Heights",
      "zone": 22,
      "code": 7000,
    },
    {
      "city": "Edmonton",
      "area": "North West",
      "name": "Pembina",
      "zone": 27,
      "code": 109,
    },
    {
      "name": "Pilot Sound Area West Portion",
      "city": "Edmonton",
    },
    {
      "name": "Pineview",
      "city": "St Albert",
    },
    {
      "name": "Pineview Fort Sask.",
      "city": "Fort Saskatchewan",
    },
    {
      "name": "Place Chaleureuse",
      "city": "Beaumont",
    },
    {
      "name": "Place La rue",
      "city": "Edmonton",
    },
    {
      "name": "Plaines Royer",
      "city": "Beaumont",
    },
    {
      "city": "Edmonton",
      "area": "South Central",
      "name": "Pleasantview_EDMO",
      "zone": 15,
      "code": 205800,
    },
    {
      "city": "Edmonton",
      "area": "South East",
      "name": "Pollard Meadows",
      "zone": 29,
      "code": 189001,
    },
    {
      "name": "Poplar Lake Estates",
      "city": "Sherwood Park",
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "Potter Greens",
      "zone": 58,
      "code": 580600,
    },
    {
      "name": "Poundmaker Indusstrial",
      "city": "Edmonton",
    },
    {
      "city": "Edmonton",
      "area": "Central",
      "name": "Prince Charles",
      "zone": 4,
      "code": 2400,
    },
    {
      "city": "Edmonton",
      "area": "Central",
      "name": "Prince Rupert",
      "zone": 8,
      "code": 3601,
    },
    {
      "name": "Pylypow Industrial",
      "city": "Edmonton",
    },
    {
      "city": "Edmonton",
      "area": "South Central",
      "name": "Queen Alexandra",
      "zone": 15,
      "code": 205100,
    },
    {
      "city": "Edmonton",
      "area": "Central",
      "name": "Queen Mary Park",
      "zone": 8,
      "code": 3603,
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "Quesnell Heights",
      "zone": 22,
      "code": 8300,
    },
    {
      "name": "Rampart Industrial",
      "city": "Edmonton",
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Ramsay Heights",
      "zone": 14,
      "code": 200403,
    },
    {
      "city": "Edmonton",
      "area": "North West",
      "name": "Rapperswill",
      "zone": 27,
      "code": 105,
    },
    {
      "name": "Regency Park_CSTS",
      "city": "Sherwood Park",
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Rhatigan Ridge",
      "zone": 14,
      "code": 200404,
    },
    {
      "city": "Edmonton",
      "area": "South East",
      "name": "Richfield",
      "zone": 29,
      "code": 188203,
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Richford",
      "zone": 55,
      "code": 550300,
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Rideau Park_EDMO",
      "zone": 16,
      "code": 206002,
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "Rio Terrace",
      "zone": 22,
      "code": 7100,
    },
    {
      "city": "Edmonton",
      "area": "South Central",
      "name": "Ritchie",
      "zone": 17,
      "code": 183800,
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "River Valley Cameron",
      "zone": 20,
      "code": 4308,
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "River Valley Capitol Hill",
      "zone": 10,
      "code": 7800,
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "River Valley Fort Edmonton",
      "zone": 14,
      "code": 140400,
    },
    {
      "city": "Edmonton",
      "area": "Central",
      "name": "River Valley Glenora",
      "zone": 11,
      "code": 8900,
    },
    {
      "city": "Edmonton",
      "area": "South Central",
      "name": "River Valley Gold Bar",
      "zone": 19,
      "code": 180504,
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "River Valley Hermitage",
      "zone": 35,
      "code": 103004,
    },
    {
      "city": "Edmonton",
      "area": "Central",
      "name": "River Valley Highlands",
      "zone": 9,
      "code": 107400,
    },
    {
      "city": "Edmonton",
      "area": "Central",
      "name": "River Valley Kinnaird",
      "zone": 9,
      "code": 106300,
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "River Valley Laurier",
      "zone": 10,
      "code": 8800,
    },
    {
      "city": "Edmonton",
      "area": "South Central",
      "name": "River Valley Mayfair",
      "zone": 15,
      "code": 150100,
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "River Valley Oleskiw",
      "zone": 22,
      "code": 7500,
    },
    {
      "city": "Edmonton",
      "area": "South Central",
      "name": "River Valley Riverside",
      "zone": 19,
      "code": 180505,
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "River Valley Rundle",
      "zone": 23,
      "code": 107700,
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "River Valley Terwillegar",
      "zone": 14,
      "code": 200412,
    },
    {
      "city": "Edmonton",
      "area": "Central",
      "name": "River Valley Victoria",
      "zone": 12,
      "code": 3609,
    },
    {
      "city": "Edmonton",
      "area": "South Central",
      "name": "River Valley Walterdale",
      "zone": 15,
      "code": 205300,
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "River Valley Whitemud",
      "zone": 14,
      "code": 200413,
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "River Valley Windermere",
      "zone": 56,
      "code": 560400,
    },
    {
      "city": "Edmonton",
      "area": "Central",
      "name": "Riverdale",
      "zone": 13,
      "code": 109200,
    },
    {
      "name": "Rosenthal Estates",
      "city": "Stony Plain",
    },
    {
      "city": "Edmonton",
      "area": "Central",
      "name": "Rossdale",
      "zone": 12,
      "code": 108500,
    },
    {
      "name": "Rossdale Industrial",
      "city": "Edmonton",
    },
    {
      "city": "Edmonton",
      "area": "North West",
      "name": "Rosslyn",
      "zone": 1,
      "code": 1300,
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Royal Gardens_EDMO",
      "zone": 16,
      "code": 200902,
    },
    {
      "name": "Ruisseau",
      "city": "Beaumont",
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "Rundle Heights",
      "zone": 23,
      "code": 108100,
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "Rural North East Horse Hills",
      "zone": 51,
      "code": 510100,
    },
    {
      "name": "Rural North East North Sturgeon",
      "city": "Edmonton",
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "Rural North East South Sturgeon",
      "zone": 51,
      "code": 510200,
    },
    {
      "name": "Rural North West",
      "city": "Edmonton",
    },
    {
      "city": "Edmonton",
      "area": "South East",
      "name": "Rural South East",
      "zone": 53,
      "code": 530000,
    },
    {
      "name": "Rural West",
      "city": "Edmonton",
    },
    {
      "city": "Edmonton",
      "area": "North West",
      "name": "Rural West Big Lake",
      "zone": 59,
      "code": 590000,
    },
    {
      "name": "Rural West Lewis Farms",
      "city": "Edmonton",
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Rutherford",
      "zone": 55,
      "code": 550500,
    },
    {
      "city": "Edmonton",
      "area": "South East",
      "name": "Sakaw",
      "zone": 29,
      "code": 188902,
    },
    {
      "city": "Edmonton",
      "area": "South East",
      "name": "Satoo",
      "zone": 29,
      "code": 188801,
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "Schonsee",
      "zone": 28,
      "code": 100005,
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "Secord",
      "zone": 58,
      "code": 581100,
    },
    {
      "name": "Shadow Ridge",
      "city": "Sherwood Park",
    },
    {
      "name": "Sheffield Industrial",
      "city": "Edmonton",
    },
    {
      "name": "Shep Industrial Park",
      "city": "Spruce Grove",
    },
    {
      "city": "Edmonton",
      "area": "Central",
      "name": "Sherbrooke",
      "zone": 4,
      "code": 2200,
    },
    {
      "name": "Sherridon Heights",
      "city": "Fort Saskatchewan",
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "Sherwood",
      "zone": 22,
      "code": 7400,
    },
    // fails
    // {
    //   "name": "Sherwood Golf & County Club",
    //   "city": "Sherwood Park",
    // },
    {
      "name": "Sherwood Heights",
      "city": "Sherwood Park",
    },
    {
      "name": "Shivan Park",
      "city": "Sherwood Park",
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "Sifton Park",
      "zone": 35,
      "code": 102905,
    },
    {
      "city": "Edmonton",
      "area": "South East",
      "name": "Silver Berry",
      "zone": 30,
      "code": 190200,
    },
    {
      "name": "Silverstone",
      "city": "Stony Plain",
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Skyrattler",
      "zone": 16,
      "code": 206201,
    },
    {
      "name": "South Business Park",
      "city": "Stony Plain",
    },
    {
      "name": "South Creek",
      "city": "Stony Plain",
    },
    {
      "city": "Edmonton",
      "area": "South East",
      "name": "South Edmonton Common",
      "zone": 41,
      "code": 185140,
    },
    {
      "name": "South Fort",
      "city": "Fort Saskatchewan",
    },
    {
      "name": "South Park",
      "city": "Leduc",
    },
    {
      "name": "South Telford",
      "city": "Leduc",
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "South Terwillegar",
      "zone": 14,
      "code": 200415,
    },
    {
      "name": "Southeast",
      "city": "Stony Plain",
    },
    {
      "name": "Southeast Industrial",
      "city": "Edmonton",
    },
    {
      "name": "Southfork",
      "city": "Leduc",
    },
    {
      "name": "Southridge_STPL",
      "city": "Stony Plain",
    },
    {
      "city": "Edmonton",
      "area": "Central",
      "name": "Spruce Avenue",
      "zone": 8,
      "code": 3602,
    },
    {
      "name": "Spruce Grove Industria Park",
      "city": "Spruce Grove",
    },
    {
      "name": "Spruce Ridge",
      "city": "Spruce Grove",
    },
    {
      "name": "Spruce Village",
      "city": "Spruce Grove",
    },
    {
      "name": "Spruce Woods",
      "city": "Spruce Grove",
    },
    {
      "name": "St. Andrews",
      "city": "Stony Plain",
    },
    {
      "city": "Edmonton",
      "area": "North West",
      "name": "Starling",
      "zone": 59,
      "code": 590600,
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Steinhauer",
      "zone": 16,
      "code": 206101,
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "Stewart Greens",
      "zone": 58,
      "code": 581000,
    },
    {
      "name": "Stone Industrial",
      "city": "Edmonton",
    },
    {
      "name": "Stoneshire",
      "city": "Spruce Grove",
    },
    {
      "city": "Edmonton",
      "area": "South Central",
      "name": "Strathcona",
      "zone": 15,
      "code": 205200,
    },
    {
      "city": "Edmonton",
      "area": "South East",
      "name": "Strathcona Industrial Park",
      "zone": 41,
      "code": 185400,
    },
    {
      "name": "Strathcona Village",
      "city": "Sherwood Park",
    },
    {
      "city": "Edmonton",
      "area": "South Central",
      "name": "Strathearn",
      "zone": 18,
      "code": 181700,
    },
    {
      "name": "Sturgeon",
      "city": "St Albert",
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "Suder Greens",
      "zone": 58,
      "code": 580900,
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "Summerlea",
      "zone": 20,
      "code": 4001,
    },
    {
      "city": "Edmonton",
      "area": "South East",
      "name": "Summerside",
      "zone": 53,
      "code": 530200,
    },
    {
      "name": "Summerwood",
      "city": "Sherwood Park",
    },
    {
      "name": "Suntree",
      "city": "Leduc",
    },
    {
      "name": "Sunwapta Industrial",
      "city": "Edmonton",
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Sweet Grass",
      "zone": 16,
      "code": 201001,
    },
    {
      "city": "Edmonton",
      "area": "South East",
      "name": "Tamarack",
      "zone": 30,
      "code": 190400,
    },
    {
      "city": "Edmonton",
      "area": "South East",
      "name": "Tawa",
      "zone": 29,
      "code": 188601,
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "Terra Losa",
      "zone": 20,
      "code": 4003,
    },
    {
      "city": "Edmonton",
      "area": "South Central",
      "name": "Terrace Heights_EDMO",
      "zone": 19,
      "code": 180400,
    },
    {
      "name": "Terwillegar Area",
      "city": "Edmonton",
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Terwillegar Towne",
      "zone": 14,
      "code": 201200,
    },
    {
      "name": "The Fairways_STPL",
      "city": "Stony Plain",
    },
    {
      "name": "The Orchards At Ellersile",
      "city": "Edmonton",
    },
    {
      "name": "The Ridge",
      "city": "Sherwood Park",
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "Thorncliffe_EDMO",
      "zone": 20,
      "code": 4002,
    },
    {
      "name": "Tiffany Greenfield",
      "city": "Stony Plain",
    },
    {
      "city": "Edmonton",
      "area": "South East",
      "name": "Tipaskan",
      "zone": 29,
      "code": 188501,
    },
    {
      "name": "Tribute",
      "city": "Leduc",
    },
    {
      "name": "Triomphe Estates",
      "city": "Beaumont",
    },
    {
      "city": "Edmonton",
      "area": "North West",
      "name": "Trumpeter Area",
      "zone": 59,
      "code": 590400,
    },
    {
      "city": "Edmonton",
      "area": "South East",
      "name": "Tweddle Place",
      "zone": 29,
      "code": 188201,
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Twin Brooks",
      "zone": 16,
      "code": 206300,
    },
    {
      "name": "University of Alberta ",
      "city": "Edmonton",
    },
    {
      "name": "University of Alberta Farm",
      "city": "Edmonton",
    },
    {
      "name": "Valley Point",
      "city": "Sherwood Park",
    },
    {
      "name": "Vegreville",
      "city": "Edmonton",
    },
    {
      "name": "Village on the Lake",
      "city": "Sherwood Park",
    },
    {
      "city": "Edmonton",
      "area": "Central",
      "name": "Virginia Park",
      "zone": 9,
      "code": 106800,
    },
    {
      "city": "Edmonton",
      "area": "South East",
      "name": "Walker",
      "zone": 53,
      "code": 530500,
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "Webber Greens",
      "zone": 58,
      "code": 580800,
    },
    {
      "name": "Webber Industrial Park",
      "city": "Spruce Grove",
    },
    {
      "name": "Wedgewood Heights ",
      "city": "Edmonton",
    },
    {
      "city": "Edmonton",
      "area": "South East",
      "name": "Weinlos",
      "zone": 29,
      "code": 188702,
    },
    {
      "name": "Weir Industrial",
      "city": "Edmonton",
    },
    {
      "city": "Edmonton",
      "area": "North West",
      "name": "Wellington",
      "zone": 1,
      "code": 1100,
    },
    {
      "name": "West Grove",
      "city": "Spruce Grove",
    },
    {
      "name": "West Haven Estates",
      "city": "Leduc",
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "West Jasper Place",
      "zone": 22,
      "code": 6100,
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "West Meadowlark Park",
      "zone": 22,
      "code": 6300,
    },
    {
      "name": "West Sheffield Industrial",
      "city": "Edmonton",
    },
    {
      "name": "Westboro",
      "city": "Sherwood Park",
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Westbrook Estate",
      "zone": 16,
      "code": 200904,
    },
    {
      "city": "Edmonton",
      "area": "Central",
      "name": "Westmount",
      "zone": 7,
      "code": 2900,
    },
    {
      "name": "Westpark_FSAS",
      "city": "Fort Saskatchewan",
    },
    {
      "city": "Edmonton",
      "area": "West",
      "name": "Westridge",
      "zone": 22,
      "code": 7200,
    },
    {
      "name": "Westview Village ",
      "city": "Edmonton",
    },
    {
      "city": "Edmonton",
      "area": "Central",
      "name": "Westwood_EDMO",
      "zone": 8,
      "code": 103900,
    },
    {
      "name": "Wetaskiwin",
      "city": "Edmonton",
    },
    {
      "name": "White Industrial",
      "city": "Edmonton",
    },
    {
      "name": "Whitecroft East",
      "city": "Sherwood Park",
    },
    {
      "name": "Whitecroft West",
      "city": "Sherwood Park",
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Whitemud Creek Ravine North",
      "zone": 14,
      "code": 200414,
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Whitemud Creek Ravine South",
      "zone": 14,
      "code": 140300,
    },
    {
      "city": "Edmonton",
      "area": "South East",
      "name": "Wild Rose",
      "zone": 30,
      "code": 190100,
    },
    {
      "name": "Willow Park_LEDU",
      "city": "Leduc",
    },
    {
      "name": "Willow Park_STPL",
      "city": "Stony Plain",
    },
    {
      "name": "Wilson Industrial",
      "city": "Edmonton",
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Windermere",
      "zone": 56,
      "code": 560100,
    },
    {
      "city": "Edmonton",
      "area": "South West",
      "name": "Windermere Area",
      "zone": 56,
      "code": 560300,
    },
    {
      "name": "Windrose",
      "city": "Leduc",
    },
    {
      "city": "Edmonton",
      "area": "South Central",
      "name": "Windsor Park_EDMO",
      "zone": 15,
      "code": 200000,
    },
    {
      "name": "Winterburn Industrial Area East",
      "city": "Edmonton",
    },
    {
      "name": "Winterburn Industrial Area West",
      "city": "Edmonton",
    },
    {
      "name": "Woodbridge Farms",
      "city": "Sherwood Park",
    },
    {
      "city": "Edmonton",
      "area": "Central",
      "name": "Woodcroft",
      "zone": 7,
      "code": 2700,
    },
    {
      "name": "Woodhaven",
      "city": "Spruce Grove",
    },
    {
      "name": "Woodlands_SALB",
      "city": "St Albert",
    },
    {
      "name": "Woodlands_STPL",
      "city": "Stony Plain",
    },
    {
      "name": "Woodside_SPGR",
      "city": "Spruce Grove",
    },
    {
      "name": "Wye Road Gardens",
      "city": "Sherwood Park",
    },
    {
      "name": "Wyecliff",
      "city": "Sherwood Park",
    },
    {
      "city": "Edmonton",
      "area": "Central",
      "name": "Yellowhead Corridor East",
      "zone": 8,
      "code": 104001,
    },
    {
      "city": "Edmonton",
      "area": "Central",
      "name": "Yellowhead Corridor West",
      "zone": 8,
      "code": 104000,
    },
    {
      "name": "Yellowhead Industrial Park",
      "city": "Spruce Grove",
    },
    {
      "city": "Edmonton",
      "area": "North East",
      "name": "York",
      "zone": 2,
      "code": 101102,
    },
    {
      "name": "Youngstown Industrial",
      "city": "Edmonton",
    },
  ],
  "fieldsMap": {
    "sAve": "benchmarkPrice",
    "sold": "sold",
    "Inventory": "active",
    "sadom": "dom",
  },
  "propertyClasses": [
    {
      "propertyName": "",
      "propertyValue": "0",
      "displayName": "residential",
    },
    {
      "propertyName": "Single Family",
      "propertyValue": "1",
      "displayName": "detached",
    },
    {
      "propertyName": "Condo",
      "propertyValue": "2",
      "displayName": "condo",
    },
  ],
}
